/**
 * AI 资源中心数据
 * 收录当前热门的 AI 大模型、MCP Servers、AI Skills/插件
 * 数据来源：综合 GitHub stars、官网热度、npm/PyPI 下载量等公开榜单
 * 注：下载量为近似值，仅用于排序展示
 */
window.AI_HUB_DATA = {
  // === 分类元信息 ===
  categories: {
    models: {
      key: 'models',
      label: 'AI 大模型',
      sub: '主流大语言模型对话平台',
      icon: '🤖',
    },
    mcp: {
      key: 'mcp',
      label: 'MCP Servers',
      sub: 'Model Context Protocol 服务',
      icon: '🔌',
    },
    skills: {
      key: 'skills',
      label: 'Skills',
      sub: 'AI 编码 / Agent Skills',
      icon: '⚡',
    },
    plugins: {
      key: 'plugins',
      label: '插件 / 扩展',
      sub: '浏览器与编辑器 AI 插件',
      icon: '🧩',
    },
  },

  // === AI 大模型对话平台 ===
  models: [
    {
      name: 'ChatGPT',
      nameEn: 'OpenAI ChatGPT',
      desc: 'OpenAI 出品的对话式 AI，GPT-4o / GPT-4.1 / o3 系列',
      url: 'https://chat.openai.com',
      icon: '💬',
      color: '#10a37f',
      tags: ['国外', '通用', '对话'],
      hot: 100,
      install: '无需安装，浏览器打开 chat.openai.com 注册账号即可使用。\n也可下载桌面端：https://openai.com/chatgpt/download/',
    },
    {
      name: 'Claude',
      nameEn: 'Anthropic Claude',
      desc: 'Anthropic 出品的长上下文 AI，对话与代码能力突出',
      url: 'https://claude.ai',
      icon: '🧠',
      color: '#d97706',
      tags: ['国外', '通用', '长上下文'],
      hot: 98,
      install: '浏览器打开 claude.ai 注册账号使用。\n也可安装 Claude 桌面端：https://claude.ai/download',
    },
    {
      name: 'Gemini',
      nameEn: 'Google Gemini',
      desc: 'Google 多模态大模型，深度集成 Workspace',
      url: 'https://gemini.google.com',
      icon: '✨',
      color: '#4285f4',
      tags: ['国外', '多模态', 'Google'],
      hot: 95,
      install: '访问 gemini.google.com 用 Google 账号登录。\nAndroid 用户可下载 Gemini App 替代 Assistant。',
    },
    {
      name: 'DeepSeek',
      nameEn: 'DeepSeek Chat',
      desc: '深度求索开源大模型，推理能力强，国内直连',
      url: 'https://chat.deepseek.com',
      icon: '🐋',
      color: '#4d6bfe',
      tags: ['国内', '开源', '推理'],
      hot: 96,
      install: '访问 chat.deepseek.com 注册即用。\n开源模型：https://huggingface.co/deepseek-ai',
    },
    {
      name: '通义千问',
      nameEn: 'Qwen',
      desc: '阿里云出品，免费 + 工具调用 + 代码模式',
      url: 'https://tongyi.aliyun.com',
      icon: '☁️',
      color: '#ff6a00',
      tags: ['国内', '免费', '阿里'],
      hot: 92,
      install: '访问 tongyi.aliyun.com 用阿里账号登录。\n开源 Qwen 模型：https://huggingface.co/Qwen',
    },
    {
      name: '文心一言',
      nameEn: 'ERNIE Bot',
      desc: '百度出品的大模型，集成搜索与百度生态',
      url: 'https://yiyan.baidu.com',
      icon: '📘',
      color: '#2932e1',
      tags: ['国内', '百度', '搜索'],
      hot: 85,
      install: '访问 yiyan.baidu.com 登录百度账号使用。\n也可下载"文小言"App。',
    },
    {
      name: '豆包',
      nameEn: 'Doubao',
      desc: '字节跳动出品，App 体验流畅，多模态能力强',
      url: 'https://www.doubao.com',
      icon: '🫘',
      color: '#0066ff',
      tags: ['国内', '字节', '多模态'],
      hot: 93,
      install: '访问 doubao.com 网页版，或下载"豆包"App。\n字节全家桶集成度高。',
    },
    {
      name: 'Kimi',
      nameEn: 'Moonshot Kimi',
      desc: '月之暗面出品，超长上下文（百万级 token）',
      url: 'https://kimi.moonshot.cn',
      icon: '🌙',
      color: '#1f1f1f',
      tags: ['国内', '长上下文', '阅读'],
      hot: 90,
      install: '访问 kimi.moonshot.cn 注册使用。\n开源 K2 模型：https://huggingface.co/moonshotai',
    },
    {
      name: '智谱清言',
      nameEn: 'Zhipu GLM',
      desc: '智谱 AI 出品，GLM-4 系列，开源开放',
      url: 'https://chatglm.cn',
      icon: '🧊',
      color: '#3859ff',
      tags: ['国内', '开源', '工具调用'],
      hot: 82,
      install: '访问 chatglm.cn 注册即用。\n开源 GLM 模型：https://huggingface.co/THUDM',
    },
    {
      name: '腾讯混元',
      nameEn: 'Tencent Hunyuan',
      desc: '腾讯出品大模型，集成微信与腾讯文档',
      url: 'https://hunyuan.tencent.com',
      icon: '🐧',
      color: '#0052d9',
      tags: ['国内', '腾讯', '多模态'],
      hot: 78,
      install: '访问 hunyuan.tencent.com 或在腾讯文档内直接调用。',
    },
    {
      name: 'Perplexity',
      nameEn: 'Perplexity AI',
      desc: 'AI 搜索引擎，答案附带引用与来源',
      url: 'https://www.perplexity.ai',
      icon: '🔍',
      color: '#1f9aaa',
      tags: ['国外', '搜索', '引用'],
      hot: 88,
      install: '访问 perplexity.ai 注册即用。\n可安装浏览器扩展：Chrome Web Store 搜索 Perplexity。',
    },
    {
      name: 'Grok',
      nameEn: 'xAI Grok',
      desc: '马斯克 xAI 出品，深度集成 X / Twitter',
      url: 'https://grok.com',
      icon: '𝕏',
      color: '#000000',
      tags: ['国外', 'xAI', '实时'],
      hot: 84,
      install: '访问 grok.com 或在 X (Twitter) App 内使用。\nX Premium 订阅可解锁更强模型。',
    },
    {
      name: 'Mistral',
      nameEn: 'Mistral Chat',
      desc: '法国 Mistral AI 开源大模型 Le Chat',
      url: 'https://chat.mistral.ai',
      icon: '🪶',
      color: '#ff7000',
      tags: ['国外', '开源', '欧洲'],
      hot: 70,
      install: '访问 chat.mistral.ai 注册使用。\n开源模型：https://huggingface.co/mistralai',
    },
    {
      name: 'Meta AI',
      nameEn: 'Meta Llama',
      desc: 'Meta 出品，集成 WhatsApp / Instagram / Facebook',
      url: 'https://www.meta.ai',
      icon: '🌐',
      color: '#0866ff',
      tags: ['国外', 'Meta', '社交'],
      hot: 75,
      install: '访问 meta.ai 或在 WhatsApp/Instagram 中直接调用。\n开源模型：https://llama.meta.com',
    },
    {
      name: 'Poe',
      nameEn: 'Quora Poe',
      desc: '一站式多模型平台，集成了多家大模型',
      url: 'https://poe.com',
      icon: '🅿️',
      color: '#5b5bd6',
      tags: ['国外', '聚合', '多模型'],
      hot: 65,
      install: '访问 poe.com 注册即用。\n支持 GPT-4o、Claude、Gemini、Llama 等多种模型。',
    },
  ],

  // === MCP Servers ===
  mcp: [
    {
      name: 'Playwright MCP',
      nameEn: '@playwright/mcp',
      desc: '微软官方 Playwright MCP，浏览器自动化 + 可访问性快照',
      url: 'https://github.com/microsoft/playwright-mcp',
      icon: '🎭',
      color: '#2eacd3',
      tags: ['浏览器', '自动化', '微软'],
      downloads: 1500000,
      install: '【Claude Desktop / Cursor 配置】\n1. 安装 Node.js 18+\n2. 编辑 claude_desktop_config.json：\n{\n  "mcpServers": {\n    "playwright": {\n      "command": "npx",\n      "args": ["-y", "@playwright/mcp@latest"]\n    }\n  }\n}\n3. 重启客户端即可使用。',
    },
    {
      name: 'Filesystem MCP',
      nameEn: '@modelcontextprotocol/server-filesystem',
      desc: '官方文件读写 MCP，授予 AI 受控的文件系统访问',
      url: 'https://github.com/modelcontextprotocol/servers',
      icon: '📁',
      color: '#7c3aed',
      tags: ['文件', '官方', '基础'],
      downloads: 1200000,
      install: '【NPM 安装】\nnpm install -g @modelcontextprotocol/server-filesystem\n\n【配置】\n{\n  "mcpServers": {\n    "filesystem": {\n      "command": "npx",\n      "args": ["-y", "@modelcontextprotocol/server-filesystem", "/path/to/allowed/dir"]\n    }\n  }\n}',
    },
    {
      name: 'GitHub MCP',
      nameEn: '@modelcontextprotocol/server-github',
      desc: 'GitHub 官方 MCP，仓库、Issue、PR 全功能操作',
      url: 'https://github.com/modelcontextprotocol/servers',
      icon: '🐙',
      color: '#24292e',
      tags: ['GitHub', '官方', '代码'],
      downloads: 980000,
      install: '【配置】\n{\n  "mcpServers": {\n    "github": {\n      "command": "npx",\n      "args": ["-y", "@modelcontextprotocol/server-github"],\n      "env": {\n        "GITHUB_PERSONAL_ACCESS_TOKEN": "<your_token>"\n      }\n    }\n  }\n}\nToken 在 https://github.com/settings/tokens 生成。',
    },
    {
      name: 'Fetch MCP',
      nameEn: '@modelcontextprotocol/server-fetch',
      desc: '网页抓取 MCP，把任意 URL 转成 LLM 可读的 Markdown',
      url: 'https://github.com/modelcontextprotocol/servers',
      icon: '🌍',
      color: '#06b6d4',
      tags: ['网络', '抓取', '官方'],
      downloads: 850000,
      install: '【配置】\n{\n  "mcpServers": {\n    "fetch": {\n      "command": "uvx",\n      "args": ["mcp-server-fetch"]\n    }\n  }\n}\n需要先安装 uv：https://docs.astral.sh/uv/',
    },
    {
      name: 'PostgreSQL MCP',
      nameEn: '@modelcontextprotocol/server-postgres',
      desc: 'PostgreSQL 数据库 MCP，只读模式查询数据库',
      url: 'https://github.com/modelcontextprotocol/servers',
      icon: '🐘',
      color: '#336791',
      tags: ['数据库', 'SQL', '官方'],
      downloads: 620000,
      install: '【配置】\n{\n  "mcpServers": {\n    "postgres": {\n      "command": "npx",\n      "args": ["-y", "@modelcontextprotocol/server-postgres", "postgresql://user:pass@host/db"]\n    }\n  }\n}',
    },
    {
      name: 'Puppeteer MCP',
      nameEn: '@modelcontextprotocol/server-puppeteer',
      desc: 'Puppeteer 浏览器自动化 MCP',
      url: 'https://github.com/modelcontextprotocol/servers',
      icon: '🎪',
      color: '#40b5a0',
      tags: ['浏览器', '自动化', '官方'],
      downloads: 540000,
      install: '【配置】\n{\n  "mcpServers": {\n    "puppeteer": {\n      "command": "npx",\n      "args": ["-y", "@modelcontextprotocol/server-puppeteer"]\n    }\n  }\n}',
    },
    {
      name: 'GitLab MCP',
      nameEn: '@modelcontextprotocol/server-gitlab',
      desc: 'GitLab 官方 MCP，项目管理与 MR 操作',
      url: 'https://github.com/modelcontextprotocol/servers',
      icon: '🦊',
      color: '#fc6d26',
      tags: ['GitLab', '官方', '代码'],
      downloads: 410000,
      install: '【配置】\n{\n  "mcpServers": {\n    "gitlab": {\n      "command": "npx",\n      "args": ["-y", "@modelcontextprotocol/server-gitlab"],\n      "env": {\n        "GITLAB_PERSONAL_ACCESS_TOKEN": "<token>",\n        "GITLAB_API_URL": "https://gitlab.com/api/v4"\n      }\n    }\n  }\n}',
    },
    {
      name: 'SQLite MCP',
      nameEn: '@modelcontextprotocol/server-sqlite',
      desc: 'SQLite 轻量数据库 MCP',
      url: 'https://github.com/modelcontextprotocol/servers',
      icon: '🗄️',
      color: '#003b57',
      tags: ['数据库', 'SQLite', '轻量'],
      downloads: 380000,
      install: '【配置】\n{\n  "mcpServers": {\n    "sqlite": {\n      "command": "uvx",\n      "args": ["mcp-server-sqlite", "--db-path", "/path/to/db.sqlite"]\n    }\n  }\n}',
    },
    {
      name: 'Brave Search MCP',
      nameEn: '@modelcontextprotocol/server-brave-search',
      desc: 'Brave 搜索引擎 MCP，提供实时联网搜索',
      url: 'https://github.com/modelcontextprotocol/servers',
      icon: '🦁',
      color: '#fb542b',
      tags: ['搜索', '联网', '官方'],
      downloads: 320000,
      install: '【配置】\n{\n  "mcpServers": {\n    "brave_search": {\n      "command": "npx",\n      "args": ["-y", "@modelcontextprotocol/server-brave-search"],\n      "env": {\n        "BRAVE_API_KEY": "<your_key>"\n      }\n    }\n  }\n}\nKey 申请：https://brave.com/search/api/',
    },
    {
      name: 'Slack MCP',
      nameEn: '@modelcontextprotocol/server-slack',
      desc: 'Slack 工作区 MCP，消息与频道操作',
      url: 'https://github.com/modelcontextprotocol/servers',
      icon: '💼',
      color: '#4a154b',
      tags: ['Slack', '办公', '官方'],
      downloads: 290000,
      install: '【配置】\n{\n  "mcpServers": {\n    "slack": {\n      "command": "npx",\n      "args": ["-y", "@modelcontextprotocol/server-slack"],\n      "env": {\n        "SLACK_BOT_TOKEN": "xoxb-...",\n        "SLACK_TEAM_ID": "T..."\n      }\n    }\n  }\n}',
    },
    {
      name: 'Context7 MCP',
      nameEn: 'upstash/context7',
      desc: 'Upstash 出品，把库文档实时拉入 LLM 上下文',
      url: 'https://github.com/upstash/context7',
      icon: '📚',
      color: '#00e9a3',
      tags: ['文档', '上下文', 'Upstash'],
      downloads: 260000,
      install: '【配置】\n{\n  "mcpServers": {\n    "context7": {\n      "command": "npx",\n      "args": ["-y", "@upstash/context7-mcp"]\n    }\n  }\n}\n使用：在 prompt 末尾加 "use context7" 即可。',
    },
    {
      name: 'Notion MCP',
      nameEn: '@notionhq/notion-mcp-server',
      desc: 'Notion 官方 MCP，页面、数据库、Block 增删改查',
      url: 'https://github.com/makenotion/notion-mcp-server',
      icon: '📝',
      color: '#000000',
      tags: ['Notion', '笔记', '官方'],
      downloads: 240000,
      install: '【配置】\n{\n  "mcpServers": {\n    "notion": {\n      "command": "npx",\n      "args": ["-y", "@notionhq/notion-mcp-server"],\n      "env": {\n        "NOTION_TOKEN": "secret_..."\n      }\n    }\n  }\n}\nToken：https://www.notion.so/profile/integrations',
    },
    {
      name: 'Docker MCP',
      nameEn: 'mcp-server-docker',
      desc: 'Docker 容器管理 MCP，启停/日志/进入容器',
      url: 'https://github.com/ckreiling/mcp-server-docker',
      icon: '🐳',
      color: '#2496ed',
      tags: ['Docker', '运维', '容器'],
      downloads: 180000,
      install: '【配置】\n{\n  "mcpServers": {\n    "docker": {\n      "command": "uvx",\n      "args": ["mcp-server-docker"]\n    }\n  }\n}\n需本地 Docker 守护进程运行。',
    },
    {
      name: 'Memory MCP',
      nameEn: '@modelcontextprotocol/server-memory',
      desc: '官方知识图谱 MCP，让 AI 拥有持久化长期记忆',
      url: 'https://github.com/modelcontextprotocol/servers',
      icon: '🧠',
      color: '#8b5cf6',
      tags: ['记忆', '知识图谱', '官方'],
      downloads: 150000,
      install: '【配置】\n{\n  "mcpServers": {\n    "memory": {\n      "command": "npx",\n      "args": ["-y", "@modelcontextprotocol/server-memory"]\n    }\n  }\n}\n数据默认存 ~/.mcp-memory/',
    },
    {
      name: 'Exa Search MCP',
      nameEn: 'exa-mcp-server',
      desc: 'Exa 神经搜索 MCP，语义级网页检索',
      url: 'https://github.com/exa-labs/exa-mcp-server',
      icon: '🛰️',
      color: '#5b21b6',
      tags: ['搜索', '语义', 'Exa'],
      downloads: 95000,
      install: '【配置】\n{\n  "mcpServers": {\n    "exa": {\n      "command": "npx",\n      "args": ["-y", "exa-mcp-server"],\n      "env": {\n        "EXA_API_KEY": "your_key"\n      }\n    }\n  }\n}\nKey：https://dashboard.exa.ai/api-keys',
    },
  ],

  // === Skills (Claude Code / Agent Skills) ===
  skills: [
    {
      name: 'claude-code-templates',
      nameEn: 'claude-code-templates',
      desc: 'Claude Code 模板集合，命令/代理/MCP 自动化脚手架',
      url: 'https://github.com/davila7/claude-code-templates',
      icon: '📋',
      color: '#ff6b35',
      tags: ['Claude', '模板', '脚手架'],
      downloads: 320000,
      install: '【一键安装】\nnpx claude-code-templates@latest\n\n或克隆仓库：\ngit clone https://github.com/davila7/claude-code-templates.git\ncd claude-code-templates && npm install',
    },
    {
      name: 'Superpowers',
      nameEn: 'superpowers',
      desc: 'Claude Code 技能库，写作/调试/审稿等专家级工作流',
      url: 'https://github.com/obra/superpowers',
      icon: '🦸',
      color: '#dc2626',
      tags: ['Claude', '工作流', '专家'],
      downloads: 210000,
      install: '【在 Claude Code 中】\n1. mkdir -p ~/.claude/skills\n2. git clone https://github.com/obra/superpowers.git ~/.claude/skills/superpowers\n3. 重启 Claude Code',
    },
    {
      name: 'Continue',
      nameEn: 'Continue.dev',
      desc: '开源 AI 编码助手，VS Code / JetBrains 全家桶',
      url: 'https://www.continue.dev',
      icon: '➡️',
      color: '#7c3aed',
      tags: ['IDE', '开源', '编码'],
      downloads: 580000,
      install: '【VS Code】\n1. 打开 VS Code\n2. 扩展商店搜索 "Continue"\n3. 点击安装\n4. 在 config.json 中配置模型 provider',
    },
    {
      name: 'Cline',
      nameEn: 'Cline (Claude Dev)',
      desc: 'VS Code Agent，可执行终端命令、读写文件、浏览器操作',
      url: 'https://github.com/cline/cline',
      icon: '🧑‍💻',
      color: '#f97316',
      tags: ['VS Code', 'Agent', '终端'],
      downloads: 720000,
      install: '【VS Code】\n1. 打开 VS Code 扩展商店\n2. 搜索 "Cline"\n3. 安装后左侧栏出现图标\n4. 配置 Anthropic/OpenAI API Key 即可使用',
    },
    {
      name: 'Aider',
      nameEn: 'Aider',
      desc: '终端 AI 结对编程，支持多语言与 Git 集成',
      url: 'https://aider.chat',
      icon: '🎯',
      color: '#16a34a',
      tags: ['CLI', '结对编程', 'Git'],
      downloads: 480000,
      install: '【Pip】\npip install aider-chat\n\n【使用】\nexport ANTHROPIC_API_KEY=sk-...\naider --model claude-sonnet-4-6 file.py',
    },
    {
      name: 'planning-with-files',
      nameEn: 'planning-with-files',
      desc: 'Claude Code 技能：把 plan 拆分成可追踪的 markdown 文件',
      url: 'https://github.com/OthmanAdi/planning-with-files',
      icon: '📅',
      color: '#0891b2',
      tags: ['Claude', '规划', 'Skills'],
      downloads: 85000,
      install: '【在 Claude Code 中】\ngit clone https://github.com/OthmanAdi/planning-with-files.git \\\n  ~/.claude/skills/planning-with-files\n重启 Claude Code 后自动加载。',
    },
    {
      name: 'Cody',
      nameEn: 'Sourcegraph Cody',
      desc: 'Sourcegraph 出品 AI 编码助手，支持全代码库上下文',
      url: 'https://sourcegraph.com/cody',
      icon: '🪁',
      color: '#ff5543',
      tags: ['IDE', '企业', '代码搜索'],
      downloads: 410000,
      install: '【VS Code / JetBrains】\n1. 扩展商店搜索 "Cody"\n2. 安装并登录 Sourcegraph 账号\n3. 关联代码仓库即可',
    },
    {
      name: 'Roo Code',
      nameEn: 'Roo Code (Roo-Cline)',
      desc: 'Cline Fork，专注多模式 Agent，自定义角色与 MCP',
      url: 'https://github.com/RooCodeInc/Roo-Code',
      icon: '🦘',
      color: '#7e22ce',
      tags: ['VS Code', 'Agent', 'MCP'],
      downloads: 290000,
      install: '【VS Code】\n1. 扩展商店搜索 "Roo Code"\n2. 安装后配置 API Key\n3. 在 ⚙️ 中启用 MCP 服务器',
    },
    {
      name: 'Kiro',
      nameEn: 'Kiro (AWS)',
      desc: 'AWS 出品的 Agentic IDE，规范驱动开发',
      url: 'https://kiro.dev',
      icon: '🪁',
      color: '#ff9900',
      tags: ['IDE', 'AWS', '规范驱动'],
      downloads: 150000,
      install: '【下载】\n访问 https://kiro.dev 下载 IDE\n支持 macOS / Windows / Linux\n登录 AWS Builder ID 即可使用',
    },
    {
      name: 'Windsurf',
      nameEn: 'Codeium Windsurf',
      desc: 'Codeium 出品 AI IDE，Cascade 代理深度集成',
      url: 'https://codeium.com/windsurf',
      icon: '🏄',
      color: '#0078d4',
      tags: ['IDE', '代理', 'Cascade'],
      downloads: 380000,
      install: '【下载】\n访问 codeium.com/windsurf 下载安装包\n支持 macOS / Windows / Linux\n注册账号后可免费使用 Cascade',
    },
  ],

  // === 插件 / 扩展（浏览器/编辑器） ===
  plugins: [
    {
      name: 'GitHub Copilot',
      nameEn: 'GitHub Copilot',
      desc: 'GitHub 官方 AI 编码助手，VS Code / JetBrains / Neovim',
      url: 'https://github.com/features/copilot',
      icon: '✈️',
      color: '#000000',
      tags: ['IDE', '官方', '付费'],
      downloads: 8000000,
      install: '【VS Code】\n1. 打开扩展商店\n2. 搜索 "GitHub Copilot"\n3. 安装并登录 GitHub 账号\n4. 个人版 $10/月，企业版 $19/月',
    },
    {
      name: 'Cursor',
      nameEn: 'Cursor',
      desc: 'AI-first 代码编辑器，VS Code Fork，深度集成 Claude/GPT',
      url: 'https://www.cursor.com',
      icon: '🎯',
      color: '#000000',
      tags: ['IDE', 'AI原生', '付费'],
      downloads: 5500000,
      install: '【下载】\n访问 cursor.com 下载安装包\n支持 macOS / Windows / Linux\nPro 版 $20/月，含最新模型',
    },
    {
      name: 'Tabnine',
      nameEn: 'Tabnine',
      desc: '老牌 AI 代码补全，本地 + 云端双模式，注重隐私',
      url: 'https://www.tabnine.com',
      icon: '🟦',
      color: '#3b82f6',
      tags: ['IDE', '补全', '隐私'],
      downloads: 4200000,
      install: '【VS Code / JetBrains】\n1. 扩展商店搜索 "Tabnine"\n2. 安装并注册账号\n3. Pro 版 $12/月，支持本地模型',
    },
    {
      name: 'Codeium',
      nameEn: 'Codeium',
      desc: '免费 AI 代码补全，70+ 语言',
      url: 'https://codeium.com',
      icon: '🌊',
      color: '#09b6bf',
      tags: ['IDE', '免费', '补全'],
      downloads: 6100000,
      install: '【VS Code】\n1. 扩展商店搜索 "Codeium"\n2. 安装后注册账号\n3. 个人完全免费，无功能限制',
    },
    {
      name: 'Monica',
      nameEn: 'Monica',
      desc: '浏览器 AI 助手侧边栏，支持 GPT-4o / Claude / Gemini',
      url: 'https://monica.im',
      icon: '🟣',
      color: '#7c3aed',
      tags: ['浏览器', '侧边栏', '聚合'],
      downloads: 3200000,
      install: '【Chrome / Edge】\n1. 访问 Chrome Web Store\n2. 搜索 "Monica"\n3. 点击 "添加至 Chrome"\n4. 注册账号后免费试用',
    },
    {
      name: 'Merlin',
      nameEn: 'Merlin AI',
      desc: '一键调用 AI 的浏览器插件，支持 30+ 模型',
      url: 'https://merlin.foyer.work',
      icon: '🪄',
      color: '#8b5cf6',
      tags: ['浏览器', '快捷键', '多模型'],
      downloads: 2100000,
      install: '【Chrome】\n1. Chrome Web Store 搜索 "Merlin AI"\n2. 点击添加，固定到工具栏\n3. Cmd/Ctrl + M 唤出',
    },
    {
      name: 'Sider',
      nameEn: 'Sider',
      desc: '浏览器侧边 AI 助手：聊天、写作、翻译、绘图一站式',
      url: 'https://sider.ai',
      icon: '🟢',
      color: '#22c55e',
      tags: ['浏览器', '侧边栏', '绘图'],
      downloads: 1900000,
      install: '【Chrome / Edge】\n1. 访问 sider.ai 下载扩展\n2. 安装后登录账号\n3. 免费版每天 30 次 GPT-3.5',
    },
    {
      name: 'MaxAI',
      nameEn: 'MaxAI',
      desc: '一键总结、回复、改写，支持自定义提示词',
      url: 'https://maxai.co',
      icon: '🔴',
      color: '#ef4444',
      tags: ['浏览器', '总结', '改写'],
      downloads: 1500000,
      install: '【Chrome / Edge / Firefox】\n1. 访问 maxai.co\n2. 选择浏览器版本安装\n3. 选中网页文字即可触发操作',
    },
    {
      name: 'HARPA AI',
      nameEn: 'HARPA AI',
      desc: '网页自动化 + AI 摘要 + SEO 监控，老牌 Chrome 插件',
      url: 'https://harpa.ai',
      icon: '🌲',
      color: '#059669',
      tags: ['浏览器', '自动化', '监控'],
      downloads: 980000,
      install: '【Chrome】\n1. Chrome Web Store 搜索 "HARPA AI"\n2. 安装后配置 API Key\n3. 任意网页按 Alt+A 唤出',
    },
    {
      name: 'You.com',
      nameEn: 'You.com',
      desc: 'AI 搜索 + 浏览器 + 侧边助手三合一',
      url: 'https://you.com',
      icon: '🔎',
      color: '#2563eb',
      tags: ['浏览器', '搜索', 'AI'],
      downloads: 1100000,
      install: '【浏览器】\n1. 访问 you.com 直接使用网页版\n2. Chrome Web Store 搜索 "You.com"\n3. 安装后默认新标签页替换',
    },
    {
      name: 'JetBrains AI',
      nameEn: 'JetBrains AI Assistant',
      desc: 'JetBrains IDE 内置 AI，深度集成代码上下文',
      url: 'https://www.jetbrains.com/ai',
      icon: '🧠',
      color: '#fe315d',
      tags: ['IDE', 'JetBrains', '集成'],
      downloads: 2300000,
      install: '【IntelliJ / PyCharm 等】\n1. Settings → Plugins → Marketplace\n2. 搜索 "AI Assistant"\n3. 安装后重启 IDE\n4. Pro 版 $10/月',
    },
    {
      name: 'Bito',
      nameEn: 'Bito',
      desc: 'IDE 插件 + CLI，多模型 AI 编码助手',
      url: 'https://bito.ai',
      icon: '🐝',
      color: '#facc15',
      tags: ['IDE', 'CLI', '免费'],
      downloads: 720000,
      install: '【VS Code / JetBrains】\n1. 扩展商店搜索 "Bito"\n2. 安装后注册账号\n3. 个人版免费，无限次使用 GPT-4o',
    },
    {
      name: 'Blackbox AI',
      nameEn: 'Blackbox',
      desc: '代码搜索 + 复制 + 提取的 AI 助手',
      url: 'https://www.blackbox.ai',
      icon: '⬛',
      color: '#0f172a',
      tags: ['IDE', '搜索', '提取'],
      downloads: 850000,
      install: '【VS Code】\n1. 扩展商店搜索 "Blackbox AI"\n2. 安装后登录\n3. 可从任何代码片段反向搜索来源',
    },
    {
      name: 'Rix',
      nameEn: 'Rix',
      desc: 'AI 搜索 + 多模型对话的浏览器伴侣',
      url: 'https://rix.ai',
      icon: '✨',
      color: '#a855f7',
      tags: ['浏览器', '搜索', '对话'],
      downloads: 480000,
      install: '【Chrome】\n1. Chrome Web Store 搜索 "Rix"\n2. 添加扩展后登录\n3. 默认新标签页替换为 Rix 搜索',
    },
  ],
};
