/**
 * AI 资源中心数据
 * 收录当前热门的 AI 大模型、MCP Servers、AI Skills/插件
 * 以及学术研究资源：科研搜索、追踪、门户与交通期刊
 * 数据来源：综合 GitHub stars、官网热度、npm/PyPI 下载量等公开榜单
 * 注：下载量为近似值，仅用于排序展示
 */
window.AI_HUB_DATA = {
  // === 分类元信息 ===
  categories: {
    models: {
      key: 'models',
      label: 'AI 大模型',
      sub: '主流大语言模型对话平台',
      icon: '🤖',
    },
    mcp: {
      key: 'mcp',
      label: 'MCP Servers',
      sub: 'Model Context Protocol 服务',
      icon: '🔌',
    },
    skills: {
      key: 'skills',
      label: 'Skills',
      sub: 'AI 编码 / Agent Skills',
      icon: '⚡',
    },
    plugins: {
      key: 'plugins',
      label: '插件 / 扩展',
      sub: '浏览器与编辑器 AI 插件',
      icon: '🧩',
    },
    academic: {
      key: 'academic',
      label: '学术研究',
      sub: '科研搜索 · 追踪 · 门户 · 交通/AI/自动驾驶 期刊',
      icon: '🎓',
      hasSubTabs: true,
      subTabs: [
        { key: 'all',              label: '全部',         icon: '📚' },
        { key: 'search',           label: '科研搜索',     icon: '🔍' },
        { key: 'tracking',         label: '科研追踪',     icon: '📡' },
        { key: 'portal',           label: '学者门户',     icon: '👤' },
        { key: 'transport-journal',label: '交通期刊',     icon: '🚦' },
        { key: 'ai-journal',       label: 'AI 期刊',      icon: '🧠' },
        { key: 'autonomous-journal', label: '自动驾驶期刊', icon: '🚗' },
      ],
    },
    finance: {
      key: 'finance',
      label: '财经',
      sub: '每日资讯 · 半导体 / CPO / 通信 / 商业航天 / 机器人',
      icon: '💹',
      hasSubTabs: true,
      subTabs: [
        { key: 'all',      label: '全部',   icon: '📊' },
        { key: 'news',     label: '综合资讯', icon: '📰' },
        { key: 'industry', label: '行业追踪', icon: '🏭' },
        { key: 'data',     label: '金融数据', icon: '📈' },
      ],
    },
  },

  // === AI 大模型对话平台 ===
  models: [
    {
      name: 'ChatGPT',
      nameEn: 'OpenAI ChatGPT',
      desc: 'OpenAI 出品的对话式 AI，GPT-4o / GPT-4.1 / o3 系列',
      url: 'https://chat.openai.com',
      icon: '💬',
      color: '#10a37f',
      tags: ['国外', '通用', '对话'],
      hot: 100,
      install: '无需安装，浏览器打开 chat.openai.com 注册账号即可使用。\n也可下载桌面端：https://openai.com/chatgpt/download/',
    },
    {
      name: 'Claude',
      nameEn: 'Anthropic Claude',
      desc: 'Anthropic 出品的长上下文 AI，对话与代码能力突出',
      url: 'https://claude.ai',
      icon: '🧠',
      color: '#d97706',
      tags: ['国外', '通用', '长上下文'],
      hot: 98,
      install: '浏览器打开 claude.ai 注册账号使用。\n也可安装 Claude 桌面端：https://claude.ai/download',
    },
    {
      name: 'Gemini',
      nameEn: 'Google Gemini',
      desc: 'Google 多模态大模型，深度集成 Workspace',
      url: 'https://gemini.google.com',
      icon: '✨',
      color: '#4285f4',
      tags: ['国外', '多模态', 'Google'],
      hot: 95,
      install: '访问 gemini.google.com 用 Google 账号登录。\nAndroid 用户可下载 Gemini App 替代 Assistant。',
    },
    {
      name: 'DeepSeek',
      nameEn: 'DeepSeek Chat',
      desc: '深度求索开源大模型，推理能力强，国内直连',
      url: 'https://chat.deepseek.com',
      icon: '🐋',
      color: '#4d6bfe',
      tags: ['国内', '开源', '推理'],
      hot: 96,
      install: '访问 chat.deepseek.com 注册即用。\n开源模型：https://huggingface.co/deepseek-ai',
    },
    {
      name: '通义千问',
      nameEn: 'Qwen',
      desc: '阿里云出品，免费 + 工具调用 + 代码模式',
      url: 'https://tongyi.aliyun.com',
      icon: '☁️',
      color: '#ff6a00',
      tags: ['国内', '免费', '阿里'],
      hot: 92,
      install: '访问 tongyi.aliyun.com 用阿里账号登录。\n开源 Qwen 模型：https://huggingface.co/Qwen',
    },
    {
      name: '文心一言',
      nameEn: 'ERNIE Bot',
      desc: '百度出品的大模型，集成搜索与百度生态',
      url: 'https://yiyan.baidu.com',
      icon: '📘',
      color: '#2932e1',
      tags: ['国内', '百度', '搜索'],
      hot: 85,
      install: '访问 yiyan.baidu.com 登录百度账号使用。\n也可下载"文小言"App。',
    },
    {
      name: '豆包',
      nameEn: 'Doubao',
      desc: '字节跳动出品，App 体验流畅，多模态能力强',
      url: 'https://www.doubao.com',
      icon: '🫘',
      color: '#0066ff',
      tags: ['国内', '字节', '多模态'],
      hot: 93,
      install: '访问 doubao.com 网页版，或下载"豆包"App。\n字节全家桶集成度高。',
    },
    {
      name: 'Kimi',
      nameEn: 'Moonshot Kimi',
      desc: '月之暗面出品，超长上下文（百万级 token）',
      url: 'https://kimi.moonshot.cn',
      icon: '🌙',
      color: '#1f1f1f',
      tags: ['国内', '长上下文', '阅读'],
      hot: 90,
      install: '访问 kimi.moonshot.cn 注册使用。\n开源 K2 模型：https://huggingface.co/moonshotai',
    },
    {
      name: '智谱清言',
      nameEn: 'Zhipu GLM',
      desc: '智谱 AI 出品，GLM-4 系列，开源开放',
      url: 'https://chatglm.cn',
      icon: '🧊',
      color: '#3859ff',
      tags: ['国内', '开源', '工具调用'],
      hot: 82,
      install: '访问 chatglm.cn 注册即用。\n开源 GLM 模型：https://huggingface.co/THUDM',
    },
    {
      name: '腾讯混元',
      nameEn: 'Tencent Hunyuan',
      desc: '腾讯出品大模型，集成微信与腾讯文档',
      url: 'https://hunyuan.tencent.com',
      icon: '🐧',
      color: '#0052d9',
      tags: ['国内', '腾讯', '多模态'],
      hot: 78,
      install: '访问 hunyuan.tencent.com 或在腾讯文档内直接调用。',
    },
    {
      name: 'Perplexity',
      nameEn: 'Perplexity AI',
      desc: 'AI 搜索引擎，答案附带引用与来源',
      url: 'https://www.perplexity.ai',
      icon: '🔍',
      color: '#1f9aaa',
      tags: ['国外', '搜索', '引用'],
      hot: 88,
      install: '访问 perplexity.ai 注册即用。\n可安装浏览器扩展：Chrome Web Store 搜索 Perplexity。',
    },
    {
      name: 'Grok',
      nameEn: 'xAI Grok',
      desc: '马斯克 xAI 出品，深度集成 X / Twitter',
      url: 'https://grok.com',
      icon: '𝕏',
      color: '#000000',
      tags: ['国外', 'xAI', '实时'],
      hot: 84,
      install: '访问 grok.com 或在 X (Twitter) App 内使用。\nX Premium 订阅可解锁更强模型。',
    },
    {
      name: 'Mistral',
      nameEn: 'Mistral Chat',
      desc: '法国 Mistral AI 开源大模型 Le Chat',
      url: 'https://chat.mistral.ai',
      icon: '🪶',
      color: '#ff7000',
      tags: ['国外', '开源', '欧洲'],
      hot: 70,
      install: '访问 chat.mistral.ai 注册使用。\n开源模型：https://huggingface.co/mistralai',
    },
    {
      name: 'Meta AI',
      nameEn: 'Meta Llama',
      desc: 'Meta 出品，集成 WhatsApp / Instagram / Facebook',
      url: 'https://www.meta.ai',
      icon: '🌐',
      color: '#0866ff',
      tags: ['国外', 'Meta', '社交'],
      hot: 75,
      install: '访问 meta.ai 或在 WhatsApp/Instagram 中直接调用。\n开源模型：https://llama.meta.com',
    },
    {
      name: 'Poe',
      nameEn: 'Quora Poe',
      desc: '一站式多模型平台，集成了多家大模型',
      url: 'https://poe.com',
      icon: '🅿️',
      color: '#5b5bd6',
      tags: ['国外', '聚合', '多模型'],
      hot: 65,
      install: '访问 poe.com 注册即用。\n支持 GPT-4o、Claude、Gemini、Llama 等多种模型。',
    },
  ],

  // === MCP Servers ===
  mcp: [
    {
      name: 'Playwright MCP',
      nameEn: '@playwright/mcp',
      desc: '微软官方 Playwright MCP，浏览器自动化 + 可访问性快照',
      url: 'https://github.com/microsoft/playwright-mcp',
      icon: '🎭',
      color: '#2eacd3',
      tags: ['浏览器', '自动化', '微软'],
      downloads: 1500000,
      install: '【Claude Desktop / Cursor 配置】\n1. 安装 Node.js 18+\n2. 编辑 claude_desktop_config.json：\n{\n  "mcpServers": {\n    "playwright": {\n      "command": "npx",\n      "args": ["-y", "@playwright/mcp@latest"]\n    }\n  }\n}\n3. 重启客户端即可使用。',
    },
    {
      name: 'Filesystem MCP',
      nameEn: '@modelcontextprotocol/server-filesystem',
      desc: '官方文件读写 MCP，授予 AI 受控的文件系统访问',
      url: 'https://github.com/modelcontextprotocol/servers',
      icon: '📁',
      color: '#7c3aed',
      tags: ['文件', '官方', '基础'],
      downloads: 1200000,
      install: '【NPM 安装】\nnpm install -g @modelcontextprotocol/server-filesystem\n\n【配置】\n{\n  "mcpServers": {\n    "filesystem": {\n      "command": "npx",\n      "args": ["-y", "@modelcontextprotocol/server-filesystem", "/path/to/allowed/dir"]\n    }\n  }\n}',
    },
    {
      name: 'GitHub MCP',
      nameEn: '@modelcontextprotocol/server-github',
      desc: 'GitHub 官方 MCP，仓库、Issue、PR 全功能操作',
      url: 'https://github.com/modelcontextprotocol/servers',
      icon: '🐙',
      color: '#24292e',
      tags: ['GitHub', '官方', '代码'],
      downloads: 980000,
      install: '【配置】\n{\n  "mcpServers": {\n    "github": {\n      "command": "npx",\n      "args": ["-y", "@modelcontextprotocol/server-github"],\n      "env": {\n        "GITHUB_PERSONAL_ACCESS_TOKEN": "<your_token>"\n      }\n    }\n  }\n}\nToken 在 https://github.com/settings/tokens 生成。',
    },
    {
      name: 'Fetch MCP',
      nameEn: '@modelcontextprotocol/server-fetch',
      desc: '网页抓取 MCP，把任意 URL 转成 LLM 可读的 Markdown',
      url: 'https://github.com/modelcontextprotocol/servers',
      icon: '🌍',
      color: '#06b6d4',
      tags: ['网络', '抓取', '官方'],
      downloads: 850000,
      install: '【配置】\n{\n  "mcpServers": {\n    "fetch": {\n      "command": "uvx",\n      "args": ["mcp-server-fetch"]\n    }\n  }\n}\n需要先安装 uv：https://docs.astral.sh/uv/',
    },
    {
      name: 'PostgreSQL MCP',
      nameEn: '@modelcontextprotocol/server-postgres',
      desc: 'PostgreSQL 数据库 MCP，只读模式查询数据库',
      url: 'https://github.com/modelcontextprotocol/servers',
      icon: '🐘',
      color: '#336791',
      tags: ['数据库', 'SQL', '官方'],
      downloads: 620000,
      install: '【配置】\n{\n  "mcpServers": {\n    "postgres": {\n      "command": "npx",\n      "args": ["-y", "@modelcontextprotocol/server-postgres", "postgresql://user:pass@host/db"]\n    }\n  }\n}',
    },
    {
      name: 'Puppeteer MCP',
      nameEn: '@modelcontextprotocol/server-puppeteer',
      desc: 'Puppeteer 浏览器自动化 MCP',
      url: 'https://github.com/modelcontextprotocol/servers',
      icon: '🎪',
      color: '#40b5a0',
      tags: ['浏览器', '自动化', '官方'],
      downloads: 540000,
      install: '【配置】\n{\n  "mcpServers": {\n    "puppeteer": {\n      "command": "npx",\n      "args": ["-y", "@modelcontextprotocol/server-puppeteer"]\n    }\n  }\n}',
    },
    {
      name: 'GitLab MCP',
      nameEn: '@modelcontextprotocol/server-gitlab',
      desc: 'GitLab 官方 MCP，项目管理与 MR 操作',
      url: 'https://github.com/modelcontextprotocol/servers',
      icon: '🦊',
      color: '#fc6d26',
      tags: ['GitLab', '官方', '代码'],
      downloads: 410000,
      install: '【配置】\n{\n  "mcpServers": {\n    "gitlab": {\n      "command": "npx",\n      "args": ["-y", "@modelcontextprotocol/server-gitlab"],\n      "env": {\n        "GITLAB_PERSONAL_ACCESS_TOKEN": "<token>",\n        "GITLAB_API_URL": "https://gitlab.com/api/v4"\n      }\n    }\n  }\n}',
    },
    {
      name: 'SQLite MCP',
      nameEn: '@modelcontextprotocol/server-sqlite',
      desc: 'SQLite 轻量数据库 MCP',
      url: 'https://github.com/modelcontextprotocol/servers',
      icon: '🗄️',
      color: '#003b57',
      tags: ['数据库', 'SQLite', '轻量'],
      downloads: 380000,
      install: '【配置】\n{\n  "mcpServers": {\n    "sqlite": {\n      "command": "uvx",\n      "args": ["mcp-server-sqlite", "--db-path", "/path/to/db.sqlite"]\n    }\n  }\n}',
    },
    {
      name: 'Brave Search MCP',
      nameEn: '@modelcontextprotocol/server-brave-search',
      desc: 'Brave 搜索引擎 MCP，提供实时联网搜索',
      url: 'https://github.com/modelcontextprotocol/servers',
      icon: '🦁',
      color: '#fb542b',
      tags: ['搜索', '联网', '官方'],
      downloads: 320000,
      install: '【配置】\n{\n  "mcpServers": {\n    "brave_search": {\n      "command": "npx",\n      "args": ["-y", "@modelcontextprotocol/server-brave-search"],\n      "env": {\n        "BRAVE_API_KEY": "<your_key>"\n      }\n    }\n  }\n}\nKey 申请：https://brave.com/search/api/',
    },
    {
      name: 'Slack MCP',
      nameEn: '@modelcontextprotocol/server-slack',
      desc: 'Slack 工作区 MCP，消息与频道操作',
      url: 'https://github.com/modelcontextprotocol/servers',
      icon: '💼',
      color: '#4a154b',
      tags: ['Slack', '办公', '官方'],
      downloads: 290000,
      install: '【配置】\n{\n  "mcpServers": {\n    "slack": {\n      "command": "npx",\n      "args": ["-y", "@modelcontextprotocol/server-slack"],\n      "env": {\n        "SLACK_BOT_TOKEN": "xoxb-...",\n        "SLACK_TEAM_ID": "T..."\n      }\n    }\n  }\n}',
    },
    {
      name: 'Context7 MCP',
      nameEn: 'upstash/context7',
      desc: 'Upstash 出品，把库文档实时拉入 LLM 上下文',
      url: 'https://github.com/upstash/context7',
      icon: '📚',
      color: '#00e9a3',
      tags: ['文档', '上下文', 'Upstash'],
      downloads: 260000,
      install: '【配置】\n{\n  "mcpServers": {\n    "context7": {\n      "command": "npx",\n      "args": ["-y", "@upstash/context7-mcp"]\n    }\n  }\n}\n使用：在 prompt 末尾加 "use context7" 即可。',
    },
    {
      name: 'Notion MCP',
      nameEn: '@notionhq/notion-mcp-server',
      desc: 'Notion 官方 MCP，页面、数据库、Block 增删改查',
      url: 'https://github.com/makenotion/notion-mcp-server',
      icon: '📝',
      color: '#000000',
      tags: ['Notion', '笔记', '官方'],
      downloads: 240000,
      install: '【配置】\n{\n  "mcpServers": {\n    "notion": {\n      "command": "npx",\n      "args": ["-y", "@notionhq/notion-mcp-server"],\n      "env": {\n        "NOTION_TOKEN": "secret_..."\n      }\n    }\n  }\n}\nToken：https://www.notion.so/profile/integrations',
    },
    {
      name: 'Docker MCP',
      nameEn: 'mcp-server-docker',
      desc: 'Docker 容器管理 MCP，启停/日志/进入容器',
      url: 'https://github.com/ckreiling/mcp-server-docker',
      icon: '🐳',
      color: '#2496ed',
      tags: ['Docker', '运维', '容器'],
      downloads: 180000,
      install: '【配置】\n{\n  "mcpServers": {\n    "docker": {\n      "command": "uvx",\n      "args": ["mcp-server-docker"]\n    }\n  }\n}\n需本地 Docker 守护进程运行。',
    },
    {
      name: 'Memory MCP',
      nameEn: '@modelcontextprotocol/server-memory',
      desc: '官方知识图谱 MCP，让 AI 拥有持久化长期记忆',
      url: 'https://github.com/modelcontextprotocol/servers',
      icon: '🧠',
      color: '#8b5cf6',
      tags: ['记忆', '知识图谱', '官方'],
      downloads: 150000,
      install: '【配置】\n{\n  "mcpServers": {\n    "memory": {\n      "command": "npx",\n      "args": ["-y", "@modelcontextprotocol/server-memory"]\n    }\n  }\n}\n数据默认存 ~/.mcp-memory/',
    },
    {
      name: 'Exa Search MCP',
      nameEn: 'exa-mcp-server',
      desc: 'Exa 神经搜索 MCP，语义级网页检索',
      url: 'https://github.com/exa-labs/exa-mcp-server',
      icon: '🛰️',
      color: '#5b21b6',
      tags: ['搜索', '语义', 'Exa'],
      downloads: 95000,
      install: '【配置】\n{\n  "mcpServers": {\n    "exa": {\n      "command": "npx",\n      "args": ["-y", "exa-mcp-server"],\n      "env": {\n        "EXA_API_KEY": "your_key"\n      }\n    }\n  }\n}\nKey：https://dashboard.exa.ai/api-keys',
    },
  ],

  // === Skills (Claude Code / Agent Skills) ===
  skills: [
    {
      name: 'claude-code-templates',
      nameEn: 'claude-code-templates',
      desc: 'Claude Code 模板集合，命令/代理/MCP 自动化脚手架',
      url: 'https://github.com/davila7/claude-code-templates',
      icon: '📋',
      color: '#ff6b35',
      tags: ['Claude', '模板', '脚手架'],
      downloads: 320000,
      install: '【一键安装】\nnpx claude-code-templates@latest\n\n或克隆仓库：\ngit clone https://github.com/davila7/claude-code-templates.git\ncd claude-code-templates && npm install',
    },
    {
      name: 'Superpowers',
      nameEn: 'superpowers',
      desc: 'Claude Code 技能库，写作/调试/审稿等专家级工作流',
      url: 'https://github.com/obra/superpowers',
      icon: '🦸',
      color: '#dc2626',
      tags: ['Claude', '工作流', '专家'],
      downloads: 210000,
      install: '【在 Claude Code 中】\n1. mkdir -p ~/.claude/skills\n2. git clone https://github.com/obra/superpowers.git ~/.claude/skills/superpowers\n3. 重启 Claude Code',
    },
    {
      name: 'Continue',
      nameEn: 'Continue.dev',
      desc: '开源 AI 编码助手，VS Code / JetBrains 全家桶',
      url: 'https://www.continue.dev',
      icon: '➡️',
      color: '#7c3aed',
      tags: ['IDE', '开源', '编码'],
      downloads: 580000,
      install: '【VS Code】\n1. 打开 VS Code\n2. 扩展商店搜索 "Continue"\n3. 点击安装\n4. 在 config.json 中配置模型 provider',
    },
    {
      name: 'Cline',
      nameEn: 'Cline (Claude Dev)',
      desc: 'VS Code Agent，可执行终端命令、读写文件、浏览器操作',
      url: 'https://github.com/cline/cline',
      icon: '🧑‍💻',
      color: '#f97316',
      tags: ['VS Code', 'Agent', '终端'],
      downloads: 720000,
      install: '【VS Code】\n1. 打开 VS Code 扩展商店\n2. 搜索 "Cline"\n3. 安装后左侧栏出现图标\n4. 配置 Anthropic/OpenAI API Key 即可使用',
    },
    {
      name: 'Aider',
      nameEn: 'Aider',
      desc: '终端 AI 结对编程，支持多语言与 Git 集成',
      url: 'https://aider.chat',
      icon: '🎯',
      color: '#16a34a',
      tags: ['CLI', '结对编程', 'Git'],
      downloads: 480000,
      install: '【Pip】\npip install aider-chat\n\n【使用】\nexport ANTHROPIC_API_KEY=sk-...\naider --model claude-sonnet-4-6 file.py',
    },
    {
      name: 'planning-with-files',
      nameEn: 'planning-with-files',
      desc: 'Claude Code 技能：把 plan 拆分成可追踪的 markdown 文件',
      url: 'https://github.com/OthmanAdi/planning-with-files',
      icon: '📅',
      color: '#0891b2',
      tags: ['Claude', '规划', 'Skills'],
      downloads: 85000,
      install: '【在 Claude Code 中】\ngit clone https://github.com/OthmanAdi/planning-with-files.git \\\n  ~/.claude/skills/planning-with-files\n重启 Claude Code 后自动加载。',
    },
    {
      name: 'Cody',
      nameEn: 'Sourcegraph Cody',
      desc: 'Sourcegraph 出品 AI 编码助手，支持全代码库上下文',
      url: 'https://sourcegraph.com/cody',
      icon: '🪁',
      color: '#ff5543',
      tags: ['IDE', '企业', '代码搜索'],
      downloads: 410000,
      install: '【VS Code / JetBrains】\n1. 扩展商店搜索 "Cody"\n2. 安装并登录 Sourcegraph 账号\n3. 关联代码仓库即可',
    },
    {
      name: 'Roo Code',
      nameEn: 'Roo Code (Roo-Cline)',
      desc: 'Cline Fork，专注多模式 Agent，自定义角色与 MCP',
      url: 'https://github.com/RooCodeInc/Roo-Code',
      icon: '🦘',
      color: '#7e22ce',
      tags: ['VS Code', 'Agent', 'MCP'],
      downloads: 290000,
      install: '【VS Code】\n1. 扩展商店搜索 "Roo Code"\n2. 安装后配置 API Key\n3. 在 ⚙️ 中启用 MCP 服务器',
    },
    {
      name: 'Kiro',
      nameEn: 'Kiro (AWS)',
      desc: 'AWS 出品的 Agentic IDE，规范驱动开发',
      url: 'https://kiro.dev',
      icon: '🪁',
      color: '#ff9900',
      tags: ['IDE', 'AWS', '规范驱动'],
      downloads: 150000,
      install: '【下载】\n访问 https://kiro.dev 下载 IDE\n支持 macOS / Windows / Linux\n登录 AWS Builder ID 即可使用',
    },
    {
      name: 'Windsurf',
      nameEn: 'Codeium Windsurf',
      desc: 'Codeium 出品 AI IDE，Cascade 代理深度集成',
      url: 'https://codeium.com/windsurf',
      icon: '🏄',
      color: '#0078d4',
      tags: ['IDE', '代理', 'Cascade'],
      downloads: 380000,
      install: '【下载】\n访问 codeium.com/windsurf 下载安装包\n支持 macOS / Windows / Linux\n注册账号后可免费使用 Cascade',
    },
  ],

  // === 插件 / 扩展（浏览器/编辑器） ===
  plugins: [
    {
      name: 'GitHub Copilot',
      nameEn: 'GitHub Copilot',
      desc: 'GitHub 官方 AI 编码助手，VS Code / JetBrains / Neovim',
      url: 'https://github.com/features/copilot',
      icon: '✈️',
      color: '#000000',
      tags: ['IDE', '官方', '付费'],
      downloads: 8000000,
      install: '【VS Code】\n1. 打开扩展商店\n2. 搜索 "GitHub Copilot"\n3. 安装并登录 GitHub 账号\n4. 个人版 $10/月，企业版 $19/月',
    },
    {
      name: 'Cursor',
      nameEn: 'Cursor',
      desc: 'AI-first 代码编辑器，VS Code Fork，深度集成 Claude/GPT',
      url: 'https://www.cursor.com',
      icon: '🎯',
      color: '#000000',
      tags: ['IDE', 'AI原生', '付费'],
      downloads: 5500000,
      install: '【下载】\n访问 cursor.com 下载安装包\n支持 macOS / Windows / Linux\nPro 版 $20/月，含最新模型',
    },
    {
      name: 'Tabnine',
      nameEn: 'Tabnine',
      desc: '老牌 AI 代码补全，本地 + 云端双模式，注重隐私',
      url: 'https://www.tabnine.com',
      icon: '🟦',
      color: '#3b82f6',
      tags: ['IDE', '补全', '隐私'],
      downloads: 4200000,
      install: '【VS Code / JetBrains】\n1. 扩展商店搜索 "Tabnine"\n2. 安装并注册账号\n3. Pro 版 $12/月，支持本地模型',
    },
    {
      name: 'Codeium',
      nameEn: 'Codeium',
      desc: '免费 AI 代码补全，70+ 语言',
      url: 'https://codeium.com',
      icon: '🌊',
      color: '#09b6bf',
      tags: ['IDE', '免费', '补全'],
      downloads: 6100000,
      install: '【VS Code】\n1. 扩展商店搜索 "Codeium"\n2. 安装后注册账号\n3. 个人完全免费，无功能限制',
    },
    {
      name: 'Monica',
      nameEn: 'Monica',
      desc: '浏览器 AI 助手侧边栏，支持 GPT-4o / Claude / Gemini',
      url: 'https://monica.im',
      icon: '🟣',
      color: '#7c3aed',
      tags: ['浏览器', '侧边栏', '聚合'],
      downloads: 3200000,
      install: '【Chrome / Edge】\n1. 访问 Chrome Web Store\n2. 搜索 "Monica"\n3. 点击 "添加至 Chrome"\n4. 注册账号后免费试用',
    },
    {
      name: 'Merlin',
      nameEn: 'Merlin AI',
      desc: '一键调用 AI 的浏览器插件，支持 30+ 模型',
      url: 'https://merlin.foyer.work',
      icon: '🪄',
      color: '#8b5cf6',
      tags: ['浏览器', '快捷键', '多模型'],
      downloads: 2100000,
      install: '【Chrome】\n1. Chrome Web Store 搜索 "Merlin AI"\n2. 点击添加，固定到工具栏\n3. Cmd/Ctrl + M 唤出',
    },
    {
      name: 'Sider',
      nameEn: 'Sider',
      desc: '浏览器侧边 AI 助手：聊天、写作、翻译、绘图一站式',
      url: 'https://sider.ai',
      icon: '🟢',
      color: '#22c55e',
      tags: ['浏览器', '侧边栏', '绘图'],
      downloads: 1900000,
      install: '【Chrome / Edge】\n1. 访问 sider.ai 下载扩展\n2. 安装后登录账号\n3. 免费版每天 30 次 GPT-3.5',
    },
    {
      name: 'MaxAI',
      nameEn: 'MaxAI',
      desc: '一键总结、回复、改写，支持自定义提示词',
      url: 'https://maxai.co',
      icon: '🔴',
      color: '#ef4444',
      tags: ['浏览器', '总结', '改写'],
      downloads: 1500000,
      install: '【Chrome / Edge / Firefox】\n1. 访问 maxai.co\n2. 选择浏览器版本安装\n3. 选中网页文字即可触发操作',
    },
    {
      name: 'HARPA AI',
      nameEn: 'HARPA AI',
      desc: '网页自动化 + AI 摘要 + SEO 监控，老牌 Chrome 插件',
      url: 'https://harpa.ai',
      icon: '🌲',
      color: '#059669',
      tags: ['浏览器', '自动化', '监控'],
      downloads: 980000,
      install: '【Chrome】\n1. Chrome Web Store 搜索 "HARPA AI"\n2. 安装后配置 API Key\n3. 任意网页按 Alt+A 唤出',
    },
    {
      name: 'You.com',
      nameEn: 'You.com',
      desc: 'AI 搜索 + 浏览器 + 侧边助手三合一',
      url: 'https://you.com',
      icon: '🔎',
      color: '#2563eb',
      tags: ['浏览器', '搜索', 'AI'],
      downloads: 1100000,
      install: '【浏览器】\n1. 访问 you.com 直接使用网页版\n2. Chrome Web Store 搜索 "You.com"\n3. 安装后默认新标签页替换',
    },
    {
      name: 'JetBrains AI',
      nameEn: 'JetBrains AI Assistant',
      desc: 'JetBrains IDE 内置 AI，深度集成代码上下文',
      url: 'https://www.jetbrains.com/ai',
      icon: '🧠',
      color: '#fe315d',
      tags: ['IDE', 'JetBrains', '集成'],
      downloads: 2300000,
      install: '【IntelliJ / PyCharm 等】\n1. Settings → Plugins → Marketplace\n2. 搜索 "AI Assistant"\n3. 安装后重启 IDE\n4. Pro 版 $10/月',
    },
    {
      name: 'Bito',
      nameEn: 'Bito',
      desc: 'IDE 插件 + CLI，多模型 AI 编码助手',
      url: 'https://bito.ai',
      icon: '🐝',
      color: '#facc15',
      tags: ['IDE', 'CLI', '免费'],
      downloads: 720000,
      install: '【VS Code / JetBrains】\n1. 扩展商店搜索 "Bito"\n2. 安装后注册账号\n3. 个人版免费，无限次使用 GPT-4o',
    },
    {
      name: 'Blackbox AI',
      nameEn: 'Blackbox',
      desc: '代码搜索 + 复制 + 提取的 AI 助手',
      url: 'https://www.blackbox.ai',
      icon: '⬛',
      color: '#0f172a',
      tags: ['IDE', '搜索', '提取'],
      downloads: 850000,
      install: '【VS Code】\n1. 扩展商店搜索 "Blackbox AI"\n2. 安装后登录\n3. 可从任何代码片段反向搜索来源',
    },
    {
      name: 'Rix',
      nameEn: 'Rix',
      desc: 'AI 搜索 + 多模型对话的浏览器伴侣',
      url: 'https://rix.ai',
      icon: '✨',
      color: '#a855f7',
      tags: ['浏览器', '搜索', '对话'],
      downloads: 480000,
      install: '【Chrome】\n1. Chrome Web Store 搜索 "Rix"\n2. 添加扩展后登录\n3. 默认新标签页替换为 Rix 搜索',
    },
  ],

  // === 学术研究 ===
  academic: [
    // ---------- 科研搜索 ----------
    {
      name: 'Google Scholar',
      nameEn: 'Google Scholar',
      desc: '最大最全的学术搜索引擎，覆盖几乎所有学科的论文、学位论文、书籍',
      url: 'https://scholar.google.com',
      icon: '🔍',
      color: '#4285f4',
      type: 'search',
      tags: ['通用', '免费', '必备'],
      install: '无需安装，浏览器访问 scholar.google.com。\n建议装 "Google Scholar Button" 浏览器扩展，\n一键搜索当前网页引用的论文。',
    },
    {
      name: 'Semantic Scholar',
      nameEn: 'Semantic Scholar',
      desc: 'AI 驱动的学术搜索，语义理解 + 引用图谱 + AI 摘要',
      url: 'https://www.semanticscholar.org',
      icon: '🧠',
      color: '#1857b8',
      type: 'search',
      tags: ['AI', '语义', '推荐'],
      install: '访问 semanticscholar.org 免费使用。\n注册后可保存文献、订阅作者新论文。\n有 Chrome 扩展 "Semantic Scholar"。',
    },
    {
      name: 'Connected Papers',
      nameEn: 'Connected Papers',
      desc: '把任意论文绘制成相关文献图谱，发现隐藏的相关研究',
      url: 'https://www.connectedpapers.com',
      icon: '🕸️',
      color: '#7c3aed',
      type: 'search',
      tags: ['图谱', '综述', '文献发现'],
      install: '访问 connectedpapers.com 即可使用。\n免费版每月 5 次，Pro 订阅 $4/月无限。',
    },
    {
      name: 'Web of Science',
      nameEn: 'Web of Science',
      desc: 'SCI/SSCI 权威引文数据库，含 JCR 影响影子、分区、引文报告',
      url: 'https://www.webofscience.com',
      icon: '🌐',
      color: '#000000',
      type: 'search',
      tags: ['SCI', '引文', '权威'],
      install: '通常通过所在高校/科研机构订阅访问。\n在校外可使用机构 VPN 或 CARSI 联邦认证登录。',
    },
    {
      name: '中国知网 CNKI',
      nameEn: 'CNKI',
      desc: '国内最大中文学术资源库，期刊、学位论文、会议、专利全覆盖',
      url: 'https://www.cnki.net',
      icon: '🇨🇳',
      color: '#cc0000',
      type: 'search',
      tags: ['中文', '学位论文', '期刊'],
      install: '访问 cnki.net 即可检索摘要。\n下载全文需机构订阅，或通过学校图书馆代理。\n桌面端有 E-Study 客户端。',
    },
    {
      name: '万方数据',
      nameEn: 'Wanfang Data',
      desc: '中文科技文献库，与知网互补，部分学位论文独家',
      url: 'https://www.wanfangdata.com.cn',
      icon: '📘',
      color: '#1e88e5',
      type: 'search',
      tags: ['中文', '学位论文', '会议'],
      install: '访问 wanfangdata.com.cn。\n机构订阅用户可下载全文。',
    },
    {
      name: 'OpenAlex',
      nameEn: 'OpenAlex',
      desc: '免费开放的学术图谱（Microsoft Graph 替代品），API 友好',
      url: 'https://openalex.org',
      icon: '🪐',
      color: '#f25022',
      type: 'search',
      tags: ['开放', 'API', '数据'],
      install: '访问 openalex.org 即可搜索。\n高级用户可调用 API：https://api.openalex.org',
    },
    {
      name: 'Inciteful',
      nameEn: 'Inciteful',
      desc: '从一篇论文出发，发现关键文献、研究脉络、作者网络',
      url: 'https://inciteful.xyz',
      icon: '💡',
      color: '#f59e0b',
      type: 'search',
      tags: ['文献发现', '图谱', '免费'],
      install: '访问 inciteful.xyz 完全免费，无需注册。\n输入论文标题/DOI 即可生成文献网络。',
    },

    // ---------- 科研追踪 ----------
    {
      name: 'Google Scholar Alerts',
      nameEn: 'Scholar Alerts',
      desc: '订阅关键词/作者新论文，邮件自动推送',
      url: 'https://scholar.google.com/scholar_alerts',
      icon: '🔔',
      color: '#4285f4',
      type: 'tracking',
      tags: ['邮件', '关键词', '作者追踪'],
      install: '1. 登录 Google 账号\n2. 在 Scholar 搜索框输入关键词/作者\n3. 点搜索栏下方 "创建快讯" 按钮\n4. 设置频率（每天/每周）',
    },
    {
      name: 'Litmaps',
      nameEn: 'Litmaps',
      desc: '可视化文献地图，自动追踪新发表的相关论文',
      url: 'https://www.litmaps.co',
      icon: '🗺️',
      color: '#0ea5e9',
      type: 'tracking',
      tags: ['地图', '追踪', '可视化'],
      install: '1. 访问 litmaps.co 注册账号\n2. 创建一个 "Litmap"，输入种子论文\n3. 平台自动发现并持续追踪相关新文献\n4. 免费版 1 个 Litmap，Pro $9/月',
    },
    {
      name: 'Scite.ai',
      nameEn: 'Scite',
      desc: 'AI 引用分析：展示论文被"支持/反对/提及"的情况',
      url: 'https://scite.ai',
      icon: '⚖️',
      color: '#22c55e',
      type: 'tracking',
      tags: ['AI', '引文分析', '立场'],
      install: '1. 访问 scite.ai 注册\n2. 搜索论文查看"引文语境"分类\n3. 装 Chrome 扩展"Scite"\n4. 看到任何论文旁直接显示引用态度',
    },
    {
      name: 'Feedly',
      nameEn: 'Feedly',
      desc: '老牌 RSS 阅读器，订阅 arXiv、期刊 RSS 即可自动收新论文',
      url: 'https://feedly.com',
      icon: '📡',
      color: '#2bb24c',
      type: 'tracking',
      tags: ['RSS', '订阅', '新闻聚合'],
      install: '1. 注册 feedly.com 账号\n2. 复制 arXiv 分类页 RSS 链接（如 https://arxiv.org/rss/cs.AI）\n3. 添加到 Feedly，左侧自动归类\n4. 配合 Leo AI 自动打标签',
    },
    {
      name: 'arXiv',
      nameEn: 'arXiv',
      desc: '预印本平台，物理/计算机/数学最新研究第一发布地',
      url: 'https://arxiv.org',
      icon: '📐',
      color: '#b31b1b',
      type: 'tracking',
      tags: ['预印本', '理工', '免费'],
      install: '1. 访问 arxiv.org 注册（机构邮箱优先）\n2. 订阅感兴趣的分类邮件（如 cs.AI, stat.ML）\n3. 或用 RSS 订阅器追踪\n4. 推荐工具：ar5iv 看 LaTeX 渲染',
    },
    {
      name: 'Connected Papers',
      nameEn: 'Connected Papers',
      desc: '也可作为追踪工具：追踪某篇论文后续被引情况',
      url: 'https://www.connectedpapers.com',
      icon: '🕸️',
      color: '#7c3aed',
      type: 'tracking',
      tags: ['图谱', '引文'],
      install: '访问 connectedpapers.com 搜索论文。\nPro 订阅可保存历史和导出。',
    },

    // ---------- 学者门户 ----------
    {
      name: 'ORCID',
      nameEn: 'ORCID',
      desc: '学术身份证，唯一标识你的所有研究成果，投稿必备',
      url: 'https://orcid.org',
      icon: '🆔',
      color: '#a6ce39',
      type: 'portal',
      tags: ['身份', '必备', '投稿'],
      install: '1. 访问 orcid.org/register\n2. 用邮箱 30 秒注册（免费）\n3. 完善个人主页，关联研究成果\n4. 投稿时填入 ORCID iD 即可自动同步',
    },
    {
      name: 'ResearchGate',
      nameEn: 'ResearchGate',
      desc: '全球学者社交网络，关注作者、问问题、读论文',
      url: 'https://www.researchgate.net',
      icon: '🌐',
      color: '#00d0af',
      type: 'portal',
      tags: ['社交', '问答', '学术圈'],
      install: '1. 用 .edu 邮箱注册可解锁更多功能\n2. 关注同领域作者、研究问题\n3. 部分论文可申请作者直接分享',
    },
    {
      name: 'AMiner',
      nameEn: 'AMiner',
      desc: '清华出品 AI 学者图谱，论文/会议/学者排行与趋势分析',
      url: 'https://www.aminer.cn',
      icon: '🧑‍🎓',
      color: '#3b5bdb',
      type: 'portal',
      tags: ['AI', '图谱', '趋势'],
      install: '1. 访问 aminer.cn 注册（推荐用清华邮箱）\n2. 查看学者/会议/期刊排行\n3. 关注学者自动收到新论文提醒\n4. 开放数据集：https://www.aminer.org/data',
    },
    {
      name: 'Google Scholar Profile',
      nameEn: 'Scholar Profile',
      desc: '个人 Google Scholar 主页，展示 h-index、引用趋势、被引排序',
      url: 'https://scholar.google.com/citations',
      icon: '📊',
      color: '#4285f4',
      type: 'portal',
      tags: ['主页', '指标', '引用'],
      install: '1. 登录 Google 账号\n2. 访问 scholar.google.com/citations\n3. 点 "创建我的学者档案"\n4. 补充文章、合并重复、设公开/不公开',
    },
    {
      name: '学术简历',
      nameEn: 'ORCID / Web of Science Researcher',
      desc: '维护学术履历的标准化平台',
      url: 'https://www.webofscience.com/wos/author/search',
      icon: '📜',
      color: '#8b5cf6',
      type: 'portal',
      tags: ['履历', '出版记录'],
      install: '通过 ORCID 或 Web of Science 账号体系。\n投稿时填 ORCID iD 自动同步。',
    },

    // ---------- 交通期刊 ----------
    {
      name: 'Transportation Research Part A',
      nameEn: 'Transportation Research Part A: Policy and Practice',
      desc: '交通政策、规划与实践，TR 系列旗舰综合刊',
      url: 'https://www.sciencedirect.com/journal/transportation-research-part-a-policy-and-practice',
      latestUrl: 'https://www.sciencedirect.com/journal/transportation-research-part-a-policy-and-practice/issues',
      icon: '🚦',
      color: '#dc2626',
      type: 'journal',
      publisher: 'Elsevier',
      if: '6.4',
      jcr: 'Q1',
      tags: ['交运', '政策', 'SCI'],
      install: '1. 通过机构订阅访问 ScienceDirect\n2. 关注期刊 RSS：https://rss.sciencedirect.com/publication/science/09658564\n3. 配合 Google Scholar Alert 追踪关键词',
    },
    {
      name: 'Transportation Research Part B',
      nameEn: 'Transportation Research Part B: Methodological',
      desc: '交通建模与方法论，运筹优化方向顶刊',
      url: 'https://www.sciencedirect.com/journal/transportation-research-part-b-methodological',
      latestUrl: 'https://www.sciencedirect.com/journal/transportation-research-part-b-methodological/issues',
      icon: '🧮',
      color: '#b91c1c',
      type: 'journal',
      publisher: 'Elsevier',
      if: '5.8',
      jcr: 'Q1',
      tags: ['交运', '方法', 'SCI'],
      install: '1. 机构订阅 ScienceDirect\n2. RSS: https://rss.sciencedirect.com/publication/science/01912615',
    },
    {
      name: 'Transportation Research Part C',
      nameEn: 'Transportation Research Part C: Emerging Technologies',
      desc: '智能交通、自动驾驶、车联网新兴技术',
      url: 'https://www.sciencedirect.com/journal/transportation-research-part-c-emerging-technologies',
      latestUrl: 'https://www.sciencedirect.com/journal/transportation-research-part-c-emerging-technologies/issues',
      icon: '🤖',
      color: '#ea580c',
      type: 'journal',
      publisher: 'Elsevier',
      if: '8.3',
      jcr: 'Q1',
      tags: ['交运', '智能交通', 'SCI'],
      install: '1. 机构订阅 ScienceDirect\n2. RSS: https://rss.sciencedirect.com/publication/science/0968090X\n3. ITS 领域投稿热门',
    },
    {
      name: 'Transportation Research Part D',
      nameEn: 'Transportation Research Part D: Transport and Environment',
      desc: '交通与环境、碳排放、可持续交通',
      url: 'https://www.sciencedirect.com/journal/transportation-research-part-d-transport-and-environment',
      latestUrl: 'https://www.sciencedirect.com/journal/transportation-research-part-d-transport-and-environment/issues',
      icon: '🌱',
      color: '#16a34a',
      type: 'journal',
      publisher: 'Elsevier',
      if: '7.3',
      jcr: 'Q1',
      tags: ['交运', '环境', '可持续'],
      install: '1. 机构订阅 ScienceDirect\n2. RSS: https://rss.sciencedirect.com/publication/science/13619209',
    },
    {
      name: 'Transportation Research Part E',
      nameEn: 'Transportation Research Part E: Logistics and Transportation Review',
      desc: '物流与运输管理，供应链方向',
      url: 'https://www.sciencedirect.com/journal/transportation-research-part-e-logistics-and-transportation-review',
      latestUrl: 'https://www.sciencedirect.com/journal/transportation-research-part-e-logistics-and-transportation-review/issues',
      icon: '📦',
      color: '#0891b2',
      type: 'journal',
      publisher: 'Elsevier',
      if: '8.0',
      jcr: 'Q1',
      tags: ['交运', '物流', 'SCI'],
      install: '1. 机构订阅 ScienceDirect\n2. RSS: https://rss.sciencedirect.com/publication/science/13665545',
    },
    {
      name: 'Transportation Research Part F',
      nameEn: 'Transportation Research Part F: Traffic Psychology and Behaviour',
      desc: '交通心理学与驾驶行为',
      url: 'https://www.sciencedirect.com/journal/transportation-research-part-f-traffic-psychology-and-behaviour',
      latestUrl: 'https://www.sciencedirect.com/journal/transportation-research-part-f-traffic-psychology-and-behaviour/issues',
      icon: '🧠',
      color: '#7c3aed',
      type: 'journal',
      publisher: 'Elsevier',
      if: '4.1',
      jcr: 'Q2',
      tags: ['交运', '心理', '行为'],
      install: '1. 机构订阅 ScienceDirect\n2. RSS: https://rss.sciencedirect.com/publication/science/13698478',
    },
    {
      name: 'Transportation Science',
      nameEn: 'Transportation Science',
      desc: 'INFORMS 旗下交通运筹顶刊，强调方法论',
      url: 'https://pubsonline.informs.org/journal/trsc',
      latestUrl: 'https://pubsonline.informs.org/toc/trsc/current',
      icon: '🧪',
      color: '#1d4ed8',
      type: 'journal',
      publisher: 'INFORMS',
      if: '5.3',
      jcr: 'Q1',
      tags: ['交运', '运筹', '顶刊'],
      install: '1. 机构订阅 INFORMS PubsOnline\n2. RSS: https://pubsonline.informs.org/action/showFeed?type=etoc&feed=rss&jc=trsc\n3. Email Alert: 在期刊页订阅 TOC',
    },
    {
      name: 'IEEE T-ITS',
      nameEn: 'IEEE Transactions on Intelligent Transportation Systems',
      desc: 'IEEE 智能交通系统汇刊，自动驾驶 / ITS 顶刊',
      url: 'https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=6979',
      latestUrl: 'https://ieeexplore.ieee.org/xpl/issues?punumber=6979',
      icon: '🚗',
      color: '#00629b',
      type: 'journal',
      publisher: 'IEEE',
      if: '8.5',
      jcr: 'Q1',
      tags: ['智能交通', '自动驾驶', '顶刊'],
      install: '1. 机构订阅 IEEE Xplore\n2. RSS: https://ieeexplore.ieee.org/rss/TOC6979.XML\n3. 注册 IEEE 账号可设置邮件提醒',
    },
    {
      name: 'Transportation Research Record',
      nameEn: 'Transportation Research Record (TRR)',
      desc: 'TRB 系列，年度海量论文，覆盖所有交通细分',
      url: 'https://journals.sagepub.com/home/trr',
      latestUrl: 'https://journals.sagepub.com/toc/trr/current',
      icon: '🛣️',
      color: '#a16207',
      type: 'journal',
      publisher: 'SAGE / TRB',
      if: '2.0',
      jcr: 'Q3',
      tags: ['交运', 'TRB', '海量'],
      install: '1. 机构订阅 SAGE\n2. RSS: https://journals.sagepub.com/action/showFeed?jc=trr&type=etoc&feed=rss\n3. TRB Annual Meeting 论文首发地',
    },
    {
      name: 'Journal of Transport Geography',
      nameEn: 'Journal of Transport Geography',
      desc: '交通地理学，城市/区域交通与空间',
      url: 'https://www.sciencedirect.com/journal/journal-of-transport-geography',
      latestUrl: 'https://www.sciencedirect.com/journal/journal-of-transport-geography/issues',
      icon: '🗺️',
      color: '#0d9488',
      type: 'journal',
      publisher: 'Elsevier',
      if: '5.9',
      jcr: 'Q1',
      tags: ['交运', '地理', '城市'],
      install: '1. 机构订阅 ScienceDirect\n2. RSS: https://rss.sciencedirect.com/publication/science/09666923',
    },
    {
      name: 'Travel Behaviour and Society',
      nameEn: 'Travel Behaviour and Society',
      desc: '出行行为与社会学，开放获取 (OA)',
      url: 'https://www.sciencedirect.com/journal/travel-behaviour-and-society',
      latestUrl: 'https://www.sciencedirect.com/journal/travel-behaviour-and-society/issues',
      icon: '🚶',
      color: '#7e22ce',
      type: 'journal',
      publisher: 'Elsevier (OA)',
      if: '6.0',
      jcr: 'Q1',
      tags: ['交运', '行为', '开放获取'],
      install: '1. 开放获取 (OA)，无需订阅直接阅读\n2. RSS: https://rss.sciencedirect.com/publication/science/2214367X',
    },
    {
      name: 'Transport Policy',
      nameEn: 'Transport Policy',
      desc: '交通政策与治理',
      url: 'https://www.sciencedirect.com/journal/transport-policy',
      latestUrl: 'https://www.sciencedirect.com/journal/transport-policy/issues',
      icon: '🏛️',
      color: '#0369a1',
      type: 'journal',
      publisher: 'Elsevier',
      if: '6.2',
      jcr: 'Q1',
      tags: ['交运', '政策', '治理'],
      install: '1. 机构订阅 ScienceDirect\n2. RSS: https://rss.sciencedirect.com/publication/science/0967070X',
    },
    {
      name: 'Accident Analysis & Prevention',
      nameEn: 'Accident Analysis & Prevention',
      desc: '交通安全与事故分析',
      url: 'https://www.sciencedirect.com/journal/accident-analysis-and-prevention',
      latestUrl: 'https://www.sciencedirect.com/journal/accident-analysis-and-prevention/issues',
      icon: '🛡️',
      color: '#dc2626',
      type: 'journal',
      publisher: 'Elsevier',
      if: '5.6',
      jcr: 'Q1',
      tags: ['交运', '安全', '事故'],
      install: '1. 机构订阅 ScienceDirect\n2. RSS: https://rss.sciencedirect.com/publication/science/00014575',
    },
    {
      name: 'Transport Reviews',
      nameEn: 'Transport Reviews',
      desc: '交通领域权威综述期刊',
      url: 'https://www.tandfonline.com/toc/ttrv20/current',
      latestUrl: 'https://www.tandfonline.com/action/issues?journalCode=ttrv20',
      icon: '📝',
      color: '#9333ea',
      type: 'journal',
      publisher: 'Taylor & Francis',
      if: '8.0',
      jcr: 'Q1',
      tags: ['交运', '综述', '顶刊'],
      install: '1. 机构订阅 T&F Online\n2. RSS: https://www.tandfonline.com/action/showFeed?type=etoc&feed=rss&jc=ttrv20',
    },
    {
      name: '中国公路学报',
      nameEn: 'China Journal of Highway and Transport',
      desc: '中国交通领域权威中文 EI 期刊',
      url: 'https://zgglxb.chd.edu.cn',
      latestUrl: 'https://zgglxb.chd.edu.cn/cn/article/doi/current',
      icon: '🇨🇳',
      color: '#dc2626',
      type: 'journal',
      publisher: '中国公路学会',
      tags: ['中文', 'EI', '交运'],
      install: '1. 访问 zgglxb.chd.edu.cn\n2. 注册后订阅邮件推送\n3. 微信公众号"中国公路学报"同步更新',
    },
    {
      name: '交通运输工程学报',
      nameEn: 'Journal of Traffic and Transportation Engineering',
      desc: '中文交通工程权威期刊',
      url: 'https://transport.chd.edu.cn',
      latestUrl: 'https://transport.chd.edu.cn/cn/article/doi/current',
      icon: '🛤️',
      color: '#7c2d12',
      type: 'journal',
      publisher: '长安大学',
      tags: ['中文', '交运'],
      install: '1. 访问 transport.chd.edu.cn\n2. 注册账号订阅推送',
    },
    {
      name: '交通运输系统工程与信息',
      nameEn: 'Journal of Transportation Systems Engineering and IT',
      desc: '中文 EI，覆盖交通系统建模与信息技术',
      url: 'https://www.tseit.ac.cn',
      latestUrl: 'https://www.tseit.ac.cn/cn/article/doi/current',
      icon: '📡',
      color: '#0e7490',
      type: 'journal',
      publisher: '中国系统工程学会',
      tags: ['中文', 'EI', '系统'],
      install: '1. 访问 tseit.ac.cn\n2. 注册订阅推送',
    },

    // ---------- AI 期刊 ----------
    {
      name: 'Nature Machine Intelligence',
      nameEn: 'Nature Machine Intelligence',
      desc: 'Nature 旗下 AI 旗舰子刊，AI 领域顶刊',
      url: 'https://www.nature.com/natmachintell/',
      latestUrl: 'https://www.nature.com/natmachintell/current-issue',
      icon: '🧠',
      color: '#ea580c',
      type: 'journal',
      field: 'ai',
      publisher: 'Nature/Springer',
      if: '25.9',
      jcr: 'Q1',
      tags: ['AI', '顶刊', 'SCI'],
      install: '1. 机构订阅 nature.com\n2. RSS: https://www.nature.com/natmachintell.rss\n3. 邮件订阅 TOC Alert',
    },
    {
      name: 'IEEE TPAMI',
      nameEn: 'IEEE TPAMI',
      desc: 'IEEE 模式分析与机器智能汇刊，CV/ML 顶刊',
      url: 'https://www.computer.org/csdl/journal/tp',
      latestUrl: 'https://www.computer.org/csdl/journal/tp/2025/01',
      icon: '🎯',
      color: '#1d4ed8',
      type: 'journal',
      field: 'ai',
      publisher: 'IEEE',
      if: '24.3',
      jcr: 'Q1',
      tags: ['AI', '模式识别', '顶刊'],
      install: '1. 机构订阅 IEEE / CSDL\n2. RSS: https://www.computer.org/csdl/journalsearch?query=tp\n3. 设置邮件 TOC 提醒',
    },
    {
      name: 'JMLR',
      nameEn: 'Journal of Machine Learning Research',
      desc: '机器学习开源旗舰期刊，论文质量极高',
      url: 'https://jmlr.org',
      latestUrl: 'https://jmlr.org/papers/v25/',
      icon: '📐',
      color: '#dc2626',
      type: 'journal',
      field: 'ai',
      publisher: 'MIT Press',
      if: '5.6',
      jcr: 'Q1',
      tags: ['机器学习', '开源', '顶刊'],
      install: '1. 访问 jmlr.org 完全免费\n2. RSS: https://jmlr.org/papers.rss\n3. 或订阅 mailing list',
    },
    {
      name: 'AIJ',
      nameEn: 'Artificial Intelligence',
      desc: 'Elsevier 旗下 AI 老牌期刊，覆盖 AI 全领域',
      url: 'https://www.sciencedirect.com/journal/artificial-intelligence',
      latestUrl: 'https://www.sciencedirect.com/journal/artificial-intelligence/issues',
      icon: '🤖',
      color: '#7c2d12',
      type: 'journal',
      field: 'ai',
      publisher: 'Elsevier',
      if: '14.0',
      jcr: 'Q1',
      tags: ['AI', '综合', 'SCI'],
      install: '1. 机构订阅 ScienceDirect\n2. RSS: https://rss.sciencedirect.com/publication/science/00043702',
    },
    {
      name: 'Neural Networks',
      nameEn: 'Neural Networks',
      desc: 'Elsevier 神经网络老牌期刊',
      url: 'https://www.sciencedirect.com/journal/neural-networks',
      latestUrl: 'https://www.sciencedirect.com/journal/neural-networks/issues',
      icon: '🕸️',
      color: '#7c3aed',
      type: 'journal',
      field: 'ai',
      publisher: 'Elsevier',
      if: '7.8',
      jcr: 'Q1',
      tags: ['神经网络', '深度学习', 'SCI'],
      install: '1. 机构订阅 ScienceDirect\n2. RSS: https://rss.sciencedirect.com/publication/science/08936080',
    },
    {
      name: 'IEEE TNNLS',
      nameEn: 'IEEE TNNLS',
      desc: '神经网络与学习系统汇刊',
      url: 'https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=5962385',
      latestUrl: 'https://ieeexplore.ieee.org/xpl/issues?punumber=5962385',
      icon: '🔬',
      color: '#0e7490',
      type: 'journal',
      field: 'ai',
      publisher: 'IEEE',
      if: '10.4',
      jcr: 'Q1',
      tags: ['神经网络', '学习系统', 'SCI'],
      install: '1. 机构订阅 IEEE Xplore\n2. RSS: https://ieeexplore.ieee.org/rss/TOC5962385.XML',
    },
    {
      name: 'Pattern Recognition',
      nameEn: 'Pattern Recognition',
      desc: 'Elsevier 模式识别老牌期刊，CV 方向重点',
      url: 'https://www.sciencedirect.com/journal/pattern-recognition',
      latestUrl: 'https://www.sciencedirect.com/journal/pattern-recognition/issues',
      icon: '🔍',
      color: '#0891b2',
      type: 'journal',
      field: 'ai',
      publisher: 'Elsevier',
      if: '8.0',
      jcr: 'Q1',
      tags: ['模式识别', 'CV', 'SCI'],
      install: '1. 机构订阅 ScienceDirect\n2. RSS: https://rss.sciencedirect.com/publication/science/00313203',
    },
    {
      name: 'Knowledge-Based Systems',
      nameEn: 'Knowledge-Based Systems',
      desc: 'KBS，知识工程与 AI 应用方向热门刊',
      url: 'https://www.sciencedirect.com/journal/knowledge-based-systems',
      latestUrl: 'https://www.sciencedirect.com/journal/knowledge-based-systems/issues',
      icon: '💎',
      color: '#a16207',
      type: 'journal',
      field: 'ai',
      publisher: 'Elsevier',
      if: '8.8',
      jcr: 'Q1',
      tags: ['知识工程', '应用', 'SCI'],
      install: '1. 机构订阅 ScienceDirect\n2. RSS: https://rss.sciencedirect.com/publication/science/09507051',
    },
    {
      name: 'Expert Systems with Applications',
      nameEn: 'ESWA',
      desc: 'Elsevier 专家系统与应用，影响影子常年 8+',
      url: 'https://www.sciencedirect.com/journal/expert-systems-with-applications',
      latestUrl: 'https://www.sciencedirect.com/journal/expert-systems-with-applications/issues',
      icon: '🎓',
      color: '#0369a1',
      type: 'journal',
      field: 'ai',
      publisher: 'Elsevier',
      if: '8.5',
      jcr: 'Q1',
      tags: ['专家系统', '应用', 'SCI'],
      install: '1. 机构订阅 ScienceDirect\n2. RSS: https://rss.sciencedirect.com/publication/science/09574174',
    },
    {
      name: 'Information Fusion',
      nameEn: 'Information Fusion',
      desc: 'Elsevier 信息融合顶刊，多模态学习方向',
      url: 'https://www.sciencedirect.com/journal/information-fusion',
      latestUrl: 'https://www.sciencedirect.com/journal/information-fusion/issues',
      icon: '🔀',
      color: '#9333ea',
      type: 'journal',
      field: 'ai',
      publisher: 'Elsevier',
      if: '18.6',
      jcr: 'Q1',
      tags: ['多模态', '融合', '顶刊'],
      install: '1. 机构订阅 ScienceDirect\n2. RSS: https://rss.sciencedirect.com/publication/science/15662535',
    },
    {
      name: 'IJCV',
      nameEn: 'International Journal of Computer Vision',
      desc: 'Springer 计算机视觉顶级期刊',
      url: 'https://link.springer.com/journal/11263',
      latestUrl: 'https://link.springer.com/journal/11263/volumes-and-issues',
      icon: '👁️',
      color: '#16a34a',
      type: 'journal',
      field: 'ai',
      publisher: 'Springer',
      if: '13.7',
      jcr: 'Q1',
      tags: ['CV', '顶刊', 'SCI'],
      install: '1. 机构订阅 Springer Link\n2. RSS: https://link.springer.com/search.rss?facet-content-type=Article&facet-journal-id=11263',
    },
    {
      name: 'CVPR',
      nameEn: 'IEEE/CVF CVPR',
      desc: '计算机视觉与模式识别会议，CCF-A',
      url: 'https://openaccess.thecvf.com/menu',
      latestUrl: 'https://openaccess.thecvf.com/Conferences/2025',
      icon: '📷',
      color: '#dc2626',
      type: 'conference',
      field: 'ai',
      publisher: 'IEEE/CVF',
      tags: ['CV', '顶会', 'CCF-A'],
      install: '1. 访问 openaccess.thecvf.com\n2. 完全开放，论文 PDF 免费\n3. 每年 6 月举办',
    },
    {
      name: 'NeurIPS',
      nameEn: 'NeurIPS',
      desc: '机器学习三大顶会之一，CCF-A',
      url: 'https://papers.nips.cc',
      latestUrl: 'https://papers.nips.cc/papers_files/paper/2024',
      icon: '🧠',
      color: '#a855f7',
      type: 'conference',
      field: 'ai',
      publisher: 'NeurIPS Foundation',
      tags: ['ML', '顶会', 'CCF-A'],
      install: '1. 访问 papers.nips.cc\n2. 完全开放\n3. 每年 12 月举办',
    },
    {
      name: 'ICML',
      nameEn: 'ICML',
      desc: '国际机器学习大会，CCF-A',
      url: 'https://proceedings.mlr.press',
      latestUrl: 'https://proceedings.mlr.press/v235/',
      icon: '📊',
      color: '#0284c7',
      type: 'conference',
      field: 'ai',
      publisher: 'PMLR',
      tags: ['ML', '顶会', 'CCF-A'],
      install: '1. 访问 proceedings.mlr.press\n2. 论文 PDF 免费\n3. 每年 7 月举办',
    },
    {
      name: 'ICLR',
      nameEn: 'ICLR',
      desc: '国际学习表征会议，深度学习顶会',
      url: 'https://openreview.net/group?id=ICLR.cc',
      latestUrl: 'https://openreview.net/group?id=ICLR.cc/Conferences/2025/Conference',
      icon: '🌀',
      color: '#0d9488',
      type: 'conference',
      field: 'ai',
      publisher: 'ICLR / OpenReview',
      tags: ['深度学习', '顶会', 'CCF-A'],
      install: '1. 访问 openreview.net 登录\n2. 进入 ICLR 2025 会议页\n3. 完全开放，Reviews 也公开',
    },
    {
      name: 'AAAI',
      nameEn: 'AAAI Conference',
      desc: '人工智能顶级综合会议，CCF-A',
      url: 'https://ojs.aaai.org/index.php/AAAI',
      latestUrl: 'https://ojs.aaai.org/index.php/AAAI/issue/view/',
      icon: '🤝',
      color: '#ea580c',
      type: 'conference',
      field: 'ai',
      publisher: 'AAAI',
      tags: ['AI', '顶会', 'CCF-A'],
      install: '1. 访问 ojs.aaai.org\n2. 论文 PDF 免费\n3. 每年 2 月举办',
    },

    // ---------- 自动驾驶期刊 ----------
    {
      name: 'IEEE T-RO',
      nameEn: 'IEEE Transactions on Robotics',
      desc: 'IEEE 机器人学汇刊，自动驾驶/机器人顶刊',
      url: 'https://www.ieee-ras.org/publications/t-ro',
      latestUrl: 'https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=8860',
      icon: '🤖',
      color: '#00629b',
      type: 'journal',
      field: 'autonomous',
      publisher: 'IEEE',
      if: '7.8',
      jcr: 'Q1',
      tags: ['机器人', '自动驾驶', 'SCI'],
      install: '1. 机构订阅 IEEE Xplore\n2. RSS: https://ieeexplore.ieee.org/rss/TOC8860.XML',
    },
    {
      name: 'IJRR',
      nameEn: 'The International Journal of Robotics Research',
      desc: '机器人研究老牌顶刊，SAGE 出版',
      url: 'https://journals.sagepub.com/home/ijr',
      latestUrl: 'https://journals.sagepub.com/toc/ijr/current',
      icon: '🦾',
      color: '#1f2937',
      type: 'journal',
      field: 'autonomous',
      publisher: 'SAGE',
      if: '7.5',
      jcr: 'Q1',
      tags: ['机器人', '顶刊', 'SCI'],
      install: '1. 机构订阅 SAGE\n2. RSS: https://journals.sagepub.com/action/showFeed?jc=ijr&type=etoc&feed=rss',
    },
    {
      name: 'Robotics and Autonomous Systems',
      nameEn: 'RAS',
      desc: 'Elsevier 机器人与自治系统',
      url: 'https://www.sciencedirect.com/journal/robotics-and-autonomous-systems',
      latestUrl: 'https://www.sciencedirect.com/journal/robotics-and-autonomous-systems/issues',
      icon: '🤖',
      color: '#dc2626',
      type: 'journal',
      field: 'autonomous',
      publisher: 'Elsevier',
      if: '5.2',
      jcr: 'Q2',
      tags: ['机器人', '自治系统', 'SCI'],
      install: '1. 机构订阅 ScienceDirect\n2. RSS: https://rss.sciencedirect.com/publication/science/09218890',
    },
    {
      name: 'Journal of Field Robotics',
      nameEn: 'Journal of Field Robotics',
      desc: 'Wiley 现场机器人，自动驾驶/野外机器人',
      url: 'https://onlinelibrary.wiley.com/journal/15564967',
      latestUrl: 'https://onlinelibrary.wiley.com/toc/15564967/current',
      icon: '🌲',
      color: '#15803d',
      type: 'journal',
      field: 'autonomous',
      publisher: 'Wiley',
      if: '6.3',
      jcr: 'Q1',
      tags: ['现场机器人', '户外', 'SCI'],
      install: '1. 机构订阅 Wiley Online\n2. RSS: https://onlinelibrary.wiley.com/feed/15564967/most-recent',
    },
    {
      name: 'Autonomous Robots',
      nameEn: 'Autonomous Robots',
      desc: 'Springer 自治机器人',
      url: 'https://link.springer.com/journal/10514',
      latestUrl: 'https://link.springer.com/journal/10514/volumes-and-issues',
      icon: '🛞',
      color: '#7c2d12',
      type: 'journal',
      field: 'autonomous',
      publisher: 'Springer',
      if: '4.0',
      jcr: 'Q2',
      tags: ['自治', '机器人', 'SCI'],
      install: '1. 机构订阅 Springer Link\n2. RSS: https://link.springer.com/search.rss?facet-content-type=Article&facet-journal-id=10514',
    },
    {
      name: 'IEEE RAM',
      nameEn: 'IEEE Robotics & Automation Magazine',
      desc: 'IEEE 机器人与自动化杂志',
      url: 'https://www.ieee-ras.org/publications/ram',
      latestUrl: 'https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=10056',
      icon: '📰',
      color: '#0891b2',
      type: 'journal',
      field: 'autonomous',
      publisher: 'IEEE',
      if: '5.2',
      jcr: 'Q1',
      tags: ['机器人', '综合', 'SCI'],
      install: '1. 机构订阅 IEEE Xplore\n2. RSS: https://ieeexplore.ieee.org/rss/TOC10056.XML',
    },
    {
      name: 'ICRA',
      nameEn: 'IEEE ICRA',
      desc: '机器人与自动化国际会议，CCF-B',
      url: 'https://www.ieee-ras.org/component/raswebshop/9-icra',
      latestUrl: 'https://ieeexplore.ieee.org/xpl/conhome/1000638/all-proceedings',
      icon: '🦿',
      color: '#00629b',
      type: 'conference',
      field: 'autonomous',
      publisher: 'IEEE',
      tags: ['机器人', '顶会', 'CCF-B'],
      install: '1. 访问 IEEE Xplore\n2. 论文 PDF 通常免费\n3. 每年 5-6 月举办',
    },
  ],

  // === 财经 ===
  finance: [
    // ---------- 综合资讯 ----------
    {
      name: '财新网',
      nameEn: 'Caixin Global',
      desc: '中国权威财经媒体，深度报道与数据',
      url: 'https://www.caixin.com',
      icon: '📰',
      color: '#cc0000',
      type: 'news',
      tags: ['综合', '深度', '权威'],
      install: '1. 访问 caixin.com\n2. 部分内容需付费会员\n3. 配套 App「财新」',
    },
    {
      name: '华尔街见闻',
      nameEn: 'Wallstreet CN',
      desc: '全球金融市场 7×24 资讯，原创分析多',
      url: 'https://wallstreetcn.com',
      icon: '📈',
      color: '#dc2626',
      type: 'news',
      tags: ['综合', '全球', '高频'],
      install: '1. 访问 wallstreetcn.com\n2. App「华尔街见闻」推送及时\n3. VIP 会员可看深度文章',
    },
    {
      name: '36氪',
      nameEn: '36Kr',
      desc: '创投资讯与新经济，覆盖科技/AI/半导体',
      url: 'https://36kr.com',
      icon: '🚀',
      color: '#0d9488',
      type: 'news',
      tags: ['创投', '科技', '新经济'],
      install: '1. 访问 36kr.com\n2. App「36氪」\n3. 关注「硬氪」「AI 频道」',
    },
    {
      name: '第一财经',
      nameEn: 'Yicai',
      desc: '上海广播电视台旗下，专业财经',
      url: 'https://www.yicai.com',
      icon: '📺',
      color: '#1e40af',
      type: 'news',
      tags: ['综合', '专业', '电视'],
      install: '1. 访问 yicai.com\n2. App「第一财经」\n3. 视频节目也不错',
    },
    {
      name: '虎嗅',
      nameEn: 'Huxiu',
      desc: '科技与商业评论',
      url: 'https://www.huxiu.com',
      icon: '🐯',
      color: '#ea580c',
      type: 'news',
      tags: ['科技', '商业', '评论'],
      install: '1. 访问 huxiu.com\n2. App「虎嗅」\n3. 热点专题质量高',
    },
    {
      name: '彭博 Bloomberg',
      nameEn: 'Bloomberg',
      desc: '全球财经资讯第一品牌',
      url: 'https://www.bloomberg.com',
      icon: '🟠',
      color: '#fa6f37',
      type: 'news',
      tags: ['全球', '金融', '权威'],
      install: '1. bloomberg.com\n2. 英文 App 推荐 Bloomberg\n3. 大量内容需订阅',
    },
    {
      name: '路透 Reuters',
      nameEn: 'Reuters',
      desc: '全球新闻通讯社，金融快讯第一',
      url: 'https://www.reuters.com',
      icon: '🟡',
      color: '#ff7300',
      type: 'news',
      tags: ['全球', '通讯社', '英文'],
      install: '1. reuters.com\n2. App「Reuters」\n3. 关注 Markets/Technology 频道',
    },
    {
      name: 'FT 金融时报',
      nameEn: 'Financial Times',
      desc: '英国老牌财经，深度分析标杆',
      url: 'https://www.ft.com',
      icon: '🟥',
      color: '#fff1e5',
      type: 'news',
      tags: ['全球', '深度', '英文'],
      install: '1. ft.com\n2. App「FT」\n3. 部分免费 + 订阅',
    },
    {
      name: 'CNBC',
      nameEn: 'CNBC',
      desc: '美国商业电视频道，实时市场数据',
      url: 'https://www.cnbc.com',
      icon: '📡',
      color: '#005594',
      type: 'news',
      tags: ['美国', '实时', '电视'],
      install: '1. cnbc.com\n2. App「CNBC」\n3. Pro 订阅可看深度数据',
    },
    {
      name: '雪球',
      nameEn: 'Xueqiu',
      desc: '中文投资社区，股票基金讨论',
      url: 'https://xueqiu.com',
      icon: '⛄',
      color: '#1d4ed8',
      type: 'news',
      tags: ['社区', '股票', '中文'],
      install: '1. xueqiu.com 注册\n2. App「雪球」\n3. 关注大 V 获取行业观点',
    },

    // ---------- 行业追踪：半导体 ----------
    {
      name: '半导体行业观察',
      nameEn: 'Semi Insights',
      desc: '半导体行业最专业的华语媒体',
      url: 'https://www.semiinsights.com',
      icon: '🔬',
      color: '#dc2626',
      type: 'industry',
      tags: ['半导体', '中文', '专业'],
      install: '1. 关注「半导体行业观察」公众号\n2. 访问 semiinsights.com\n3. 每日推送行业新闻',
    },
    {
      name: '芯智讯',
      nameEn: 'icsmart',
      desc: '芯片与电子产业链资讯',
      url: 'https://www.icsmart.cn',
      icon: '💠',
      color: '#7c3aed',
      type: 'industry',
      tags: ['半导体', '中文', '芯片'],
      install: '1. 关注「芯智讯」公众号\n2. 访问 icsmart.cn\n3. 覆盖芯片设计/制造/封测',
    },
    {
      name: 'TrendForce',
      nameEn: 'TrendForce 集邦',
      desc: '全球存储/晶圆/封测权威数据机构',
      url: 'https://www.trendforce.com',
      icon: '📊',
      color: '#0d9488',
      type: 'industry',
      tags: ['半导体', '数据', '全球'],
      install: '1. trendforce.com\n2. 英文为主，部分繁体\n3. 报告需付费订阅',
    },
    {
      name: 'IC Insights',
      nameEn: 'IC Insights',
      desc: '半导体行业研究与排名',
      url: 'https://www.icinsights.com',
      icon: '🏭',
      color: '#0369a1',
      type: 'industry',
      tags: ['半导体', '研究', '英文'],
      install: '1. icinsights.com\n2. 深度报告付费\n3. 每月 McClean Report 行业风向标',
    },
    {
      name: 'SEMI',
      nameEn: 'SEMI 半导体协会',
      desc: '全球半导体设备与材料协会官方',
      url: 'https://www.semi.org',
      icon: '🏗️',
      color: '#0891b2',
      type: 'industry',
      tags: ['半导体', '设备', '材料'],
      install: '1. semi.org\n2. 行业活动 World Fab Forecast\n3. 季报预测产能',
    },

    // ---------- 行业追踪：CPO / 光通信 ----------
    {
      name: '讯石光通信网',
      nameEn: 'Fiberstore',
      desc: '光通信行业专业媒体，CPO/光模块重点',
      url: 'https://www.fiberstore.com/news',
      icon: '💡',
      color: '#f59e0b',
      type: 'industry',
      tags: ['CPO', '光通信', '中文'],
      install: '1. 关注「讯石光通讯」公众号\n2. 访问 fiberstore.com\n3. 每日光模块行情',
    },
    {
      name: 'LightCounting',
      nameEn: 'LightCounting',
      desc: '全球光通信权威研究机构',
      url: 'https://www.lightcounting.com',
      icon: '🔆',
      color: '#ea580c',
      type: 'industry',
      tags: ['CPO', '光模块', '英文'],
      install: '1. lightcounting.com\n2. 报告付费\n3. 季度报告权威',
    },
    {
      name: 'C114 通信网',
      nameEn: 'C114',
      desc: '通信行业头部中文媒体',
      url: 'https://www.c114.com.cn',
      icon: '📞',
      color: '#0284c7',
      type: 'industry',
      tags: ['通信', '中文', '综合'],
      install: '1. c114.com.cn\n2. App「C114」\n3. 覆盖运营商/设备商/光模块',
    },
    {
      name: '讯飞光模块行情',
      nameEn: 'CPO Tracker',
      desc: '800G/1.6T 光模块最新动态聚合',
      url: 'https://www.lightcounting.com/market-research-1',
      icon: '🌐',
      color: '#a855f7',
      type: 'industry',
      tags: ['CPO', '1.6T', '英文'],
      install: '1. 订阅 LightCounting 邮件\n2. 跟踪 NVIDIA/博通/Coherent 公告\n3. 关注 OFC/ECOC 会议',
    },

    // ---------- 行业追踪：通信 ----------
    {
      name: '通信世界',
      nameEn: 'Communications World',
      desc: '通信行业权威中文杂志',
      url: 'https://www.cww.net.cn',
      icon: '📡',
      color: '#0369a1',
      type: 'industry',
      tags: ['通信', '中文', '杂志'],
      install: '1. cww.net.cn\n2. 关注「通信世界」公众号\n3. 覆盖 5G/6G/卫星通信',
    },
    {
      name: '人民邮电报',
      nameEn: 'CNII',
      desc: '工信部主管权威通信媒体',
      url: 'https://www.cnii.com.cn',
      icon: '🗞️',
      color: '#dc2626',
      type: 'industry',
      tags: ['通信', '官方', '政策'],
      install: '1. cnii.com.cn\n2. 关注「人民邮电报」公众号\n3. 政策与产业新闻',
    },
    {
      name: 'IEEE Communications',
      nameEn: 'IEEE Communications Society',
      desc: '通信领域 IEEE 官方',
      url: 'https://www.comsoc.org',
      icon: '🌍',
      color: '#00629b',
      type: 'industry',
      tags: ['通信', '国际', '学术'],
      install: '1. comsoc.org\n2. 关注 ICC/Globecom 顶会\n3. 订阅通信标准动态',
    },

    // ---------- 行业追踪：商业航天 ----------
    {
      name: '航天爱好者网',
      nameEn: 'Spacefans',
      desc: '中文商业航天头部社区',
      url: 'https://www.spacefans.net',
      icon: '🚀',
      color: '#1e3a8a',
      type: 'industry',
      tags: ['商业航天', '中文', '社区'],
      install: '1. 关注「航天爱好者」公众号\n2. 访问 spacefans.net\n3. 国内外航天发射实时动态',
    },
    {
      name: '商业航天在线',
      nameEn: 'Business Space',
      desc: '商业航天产业资讯平台',
      url: 'https://www.business-space.com',
      icon: '🛰️',
      color: '#0891b2',
      type: 'industry',
      tags: ['商业航天', '中文', '产业'],
      install: '1. business-space.com\n2. 关注「商业航天」公众号\n3. 投融资/政策/技术',
    },
    {
      name: 'SpaceNews',
      nameEn: 'SpaceNews',
      desc: '全球商业航天权威英文媒体',
      url: 'https://spacenews.com',
      icon: '🛸',
      color: '#0d9488',
      type: 'industry',
      tags: ['商业航天', '全球', '英文'],
      install: '1. spacenews.com\n2. 订阅 newsletter\n3. 覆盖 SpaceX/Rocket Lab/ULA',
    },
    {
      name: 'NASASpaceflight',
      nameEn: 'NASASpaceflight',
      desc: '航天技术深度报道 + 论坛',
      url: 'https://www.nasaspaceflight.com',
      icon: '🪐',
      color: '#7c2d12',
      type: 'industry',
      tags: ['航天', '技术', '英文'],
      install: '1. nasaspaceflight.com\n2. 论坛 NSF 社区活跃\n3. 发射直播/技术分析',
    },

    // ---------- 行业追踪：机器人 ----------
    {
      name: '机器人大讲堂',
      nameEn: 'Robotics China',
      desc: '中文机器人产业资讯与投资分析',
      url: 'https://www.roboticschina.com',
      icon: '🦾',
      color: '#dc2626',
      type: 'industry',
      tags: ['机器人', '中文', '投资'],
      install: '1. 关注「机器人大讲堂」公众号\n2. roboticschina.com\n3. 覆盖人形/工业/医疗机器人',
    },
    {
      name: '高工机器人',
      nameEn: 'GG Robot',
      desc: '机器人产业链深度报道',
      url: 'https://www.gg-robot.com',
      icon: '⚙️',
      color: '#7c2d12',
      type: 'industry',
      tags: ['机器人', '中文', '产业链'],
      install: '1. gg-robot.com\n2. 关注「高工机器人」公众号\n3. 行业研报质量高',
    },
    {
      name: 'The Robot Report',
      nameEn: 'The Robot Report',
      desc: '全球机器人/AI 行业新闻',
      url: 'https://www.therobotreport.com',
      icon: '🤖',
      color: '#0e7490',
      type: 'industry',
      tags: ['机器人', '全球', '英文'],
      install: '1. therobotreport.com\n2. 订阅 newsletter\n3. 覆盖人形/协作/AMR',
    },
    {
      name: 'IEEE Spectrum 机器人',
      nameEn: 'IEEE Spectrum Robotics',
      desc: 'IEEE 旗下机器人/AI 专题',
      url: 'https://spectrum.ieee.org/robotics',
      icon: '🧪',
      color: '#00629b',
      type: 'industry',
      tags: ['机器人', '技术', '英文'],
      install: '1. spectrum.ieee.org/robotics\n2. 高质量技术文章\n3. 每周更新',
    },

    // ---------- 金融数据 ----------
    {
      name: '同花顺',
      nameEn: '10jqka',
      desc: '国内最常用股票行情软件',
      url: 'https://www.10jqka.com.cn',
      icon: '📊',
      color: '#dc2626',
      type: 'data',
      tags: ['股票', '中文', '行情'],
      install: '1. 同花顺 App/PC 客户端\n2. 覆盖 A 股/港股/美股\n3. i 问财 AI 选股',
    },
    {
      name: '东方财富',
      nameEn: 'East Money',
      desc: '财经门户 + 行情数据 + 研报',
      url: 'https://www.eastmoney.com',
      icon: '💰',
      color: '#dc2626',
      type: 'data',
      tags: ['股票', '研报', '行情'],
      install: '1. 东方财富 App/PC\n2. Choice 终端专业数据\n3. 研报中心免费看摘要',
    },
    {
      name: '富途牛牛',
      nameEn: 'Futu NiuNiu',
      desc: '港股美股开户与行情',
      url: 'https://www.futunn.com',
      icon: '🐂',
      color: '#0284c7',
      type: 'data',
      tags: ['港股', '美股', '券商'],
      install: '1. 富途 App\n2. 港美股实时行情\n3. 社区牛牛圈',
    },
    {
      name: '老虎证券',
      nameEn: 'Tiger Brokers',
      desc: '美港股交易与数据',
      url: 'https://www.itiger.com',
      icon: '🐯',
      color: '#ea580c',
      type: 'data',
      tags: ['美股', '港股', '券商'],
      install: '1. Tiger Trade App\n2. 美港股实时行情\n3. 社区讨论',
    },
    {
      name: 'Wind 万得',
      nameEn: 'Wind',
      desc: '国内机构级金融数据终端',
      url: 'https://www.wind.com.cn',
      icon: '🌐',
      color: '#1e40af',
      type: 'data',
      tags: ['机构', '数据', '专业'],
      install: '1. wind.com.cn\n2. 机构订阅，个人价格较高\n3. 部分高校有校园 license',
    },
    {
      name: 'Bloomberg Terminal',
      nameEn: 'Bloomberg',
      desc: '全球金融数据黄金标准',
      url: 'https://www.bloomberg.com/professional',
      icon: '🟧',
      color: '#fa6f37',
      type: 'data',
      tags: ['全球', '终端', '专业'],
      install: '1. Bloomberg Terminal\n2. 需机构订阅（≈$24k/年/账号）\n3. 部分学校提供给学生',
    },
    {
      name: '雪球行情',
      nameEn: 'Xueqiu Quote',
      desc: '雪球行情 + 组合',
      url: 'https://xueqiu.com/hq',
      icon: '⛄',
      color: '#1d4ed8',
      type: 'data',
      tags: ['股票', '社区', '组合'],
      install: '1. xueqiu.com 注册\n2. 关注组合 + 实盘\n3. 看大 V 调仓',
    },
  ],
};
